<template>
  <div id="some-id">
    <section>
      <div class="relative py-4">
        <div class="mx-auto max-w-7xl lg:px-4 px-2">
          <input type="text" placeholder="Enter text here" class="dark:bg-dark-900 h-11 w-full rounded-lg border border-gray-300 bg-transparent px-4 py-2.5 text-sm text-gray-800 shadow-theme-xs placeholder:text-gray-400 focus:border-brand-300 focus:outline-hidden focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90 dark:placeholder:text-white/30 dark:focus:border-brand-800" />

        </div>
      </div>
    </section>
  </div>
  <button @click="addComponentToBuilder" class="mt-2 bg-blue-500 text-white px-4 py-2 rounded">Click Me</button>
  <section>
    <div class="relative py-4">
      <div class="mx-auto max-w-7xl lg:px-4 px-2">
        Two
      </div>
    </div>
  </section>
</template>
<script setup lang="ts">
import { getPageBuilder, usePageBuilderModal } from '@myissue/vue-website-page-builder'

const pageBuilderService = getPageBuilder()
const { closeAddComponentModal } = usePageBuilderModal()

const addComponentToBuilder = async function () {
const container: HTMLDivElement = document.getElementById("some-id") as HTMLDivElement;
  const component = {
    // ID will be auto-generated by the Page Builder
    id: null,
    html_code: container.innerHTML,
    title: 'Header Example One',
  }

  await injectComponentToBuilder(component)
  closeAddComponentModal()
}
const injectComponentToBuilder = async function (componentObject: { html_code: string; title: string }) {
  const component = {
    // ID will be auto-generated by the Page Builder
    id: null,
    html_code: componentObject.html_code,
    title: componentObject.title,
  }

  await pageBuilderService.addComponent(component)
  closeAddComponentModal()
}

</script>