services:

  sesame-db:
    image: "postgres:latest"
    env_file:
      - ./backend/environment/.env.development    
    container_name: sesame-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: 5435
    command:
      - postgres
      - -c
      - ssl=off      
    ports:
      - 5435:5435
    networks:
      - sesame-network
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    volumes:
      - pgdata:/var/lib/postgresql           
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sesame_supertokens_user", "-d", "supertokens"]
      interval: 5s
      timeout: 5s
      retries: 5

  sesame-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sesame-frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules    
    ports:
      - "8001:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - sesame-network

  sesame-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sesame-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules   
    ports:
      - "3001:3001"
    depends_on:
      sesame-db:
        condition: service_healthy
    networks:
      - sesame-network

  sesame-supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    env_file:
      - ./backend/environment/.env.development
    container_name: sesame-supertokens
    depends_on:
      sesame-db:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: ${PG_CONNECTION_STRING_SUPER_TOKENS}
    networks:
      - sesame-network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c "exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello""
      interval: 10s
      timeout: 5s
      retries: 5

  sesame-pgadmin:
    image: dpage/pgadmin4:9.14
    env_file:
      - ./backend/environment/.env.development    
    container_name: sesame-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - sesame-network      
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - sesame-db
    restart: always      

networks:
  sesame-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data: 
  frontend_node_modules:
  backend_node_modules:   