--DROP TABLE Event_Type, Organization, Venue, Event, Attendee, Event_Tickets, Roles, Employee, Partner, Event_Partner, Event_Employee, Event_Ticket_Assignment; 
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Event_Type 
(
	  event_type_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  event_type_name VARCHAR(50) NULL
);
COMMENT ON TABLE Event_Type IS 'Table to store different types of events';

--DROP TABLE Organization CASCADE; 
CREATE TABLE Organization 
(
	  organization_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  name VARCHAR(50) NOT NULL,
	  contact_person VARCHAR(50) ,
	  email VARCHAR(50) NOT NULL,
	  phone VARCHAR(25) NULL
);
COMMENT ON TABLE Organization IS 'Table to store information about organizations';

--DROP TABLE Venue;
CREATE TABLE Venue
(
	  venue_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  capacity INT NOT NULL, 
	  address_line VARCHAR(60) NULL,
	  city VARCHAR(30) NULL, 
	  state VARCHAR(30) NULL, 
	  postal_code VARCHAR(15) NULL, 
	  country VARCHAR(30) NULL
);
COMMENT ON TABLE Venue IS 'Table to store information about venues';

--DROP TABLE Event;
CREATE TABLE Event 
(
	  event_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  event_Type_ID INT NOT NULL,
	  organization_ID INT  NOT NULL,
	  venue_ID INT NOT NULL,
	  start_date DATE NOT NULL,
	  end_date DATE NULL,
	  budget_estimated MONEY NULL,
	  total_expenditure MONEY NULL,
	  description TEXT NULL,
	  status VARCHAR(20) NULL,
	  estimated_attendance INT NULL,
	  actual_attendance INT NULL,
	  FOREIGN KEY (event_Type_ID) REFERENCES Event_Type(event_Type_ID),
	  FOREIGN KEY (organization_ID) REFERENCES Organization(organization_ID),
	  FOREIGN KEY (venue_ID) REFERENCES Venue(venue_ID)
);
COMMENT ON TABLE Event IS 'Table to store information about events';


ALTER TABLE Venue
ADD OnlineFlag BIT;

--DROP TABLE Attendee;
CREATE TABLE Attendee 
(
	  attendee_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  first_name  VARCHAR(50) NOT NULL,
	  last_name VARCHAR(50) NOT NULL,
	  email VARCHAR(50) NOT NULL,
	  phone VARCHAR(25) NULL
);
COMMENT ON TABLE Attendee IS 'Table to store information about attendees';

--DROP TABLE Event_Tickets; 
CREATE TABLE Event_Tickets 
(
	ticket_ID uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	event_ID INT NOT NULL,
	ticket_type VARCHAR(50),
	price MONEY,
	FOREIGN KEY (event_ID) REFERENCES Event(event_ID)
);
COMMENT ON TABLE Event_Tickets IS 'Table to store information about event tickets';
/*
ALTER TABLE Event_Tickets
ADD CONSTRAINT PK_ticket_ID
PRIMARY KEY(ticket_ID);
*/

--DROP TABLE Roles;
CREATE TABLE Roles
(
	role_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	role_name VARCHAR(50) NOT NULL
);
COMMENT ON TABLE Roles IS 'Table to store different user roles'; 

--DROP TABLE Employee;
CREATE TABLE Employee 
(
	  employee_ID  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  organization_ID  INT NOT NULL,
		role_ID INT NOT NULL, 
	  first_name VARCHAR(50) NOT NULL,
	  last_name VARCHAR(50) NOT NULL,
	  job_title VARCHAR(50) NOT NULL,
	  email VARCHAR(50) NOT NULL,
	  FOREIGN KEY (organization_ID) REFERENCES Organization(organization_ID),
		FOREIGN KEY (role_ID) REFERENCES Roles(role_ID)
);
COMMENT ON TABLE Employee IS 'Table to store information about employees';

--DROP TABLE Partner;
CREATE TABLE Partner 
(
	  partner_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  name VARCHAR(50) NOT NULL,
	  email VARCHAR(50) NOT NULL,
	  phone VARCHAR(25) NULL
);
COMMENT ON TABLE Partner IS 'Table to store information about partners';

--DROP TABLE Event_Partner;
CREATE TABLE Event_Partner
(
	  event_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  partner_ID INT  NOT NULL,
	  role VARCHAR(50) NOT NULL,
	  FOREIGN KEY (partner_ID) REFERENCES Partner(Partner_ID)
);
COMMENT ON TABLE Event_Partner IS 'Junction table: one event many partners, one partner many events';

--DROP TABLE Event_Employee; 
CREATE TABLE Event_Employee 
(
	  event_ID INT NOT NULL,
	  employee_ID INT NOT NULL,
	  task VARCHAR(120) NULL,
	  start_date DATE NULL,
	  deadline DATE NULL,
	  task_completed BIT NULL,
	  FOREIGN KEY (event_ID) REFERENCES Event(Event_ID),
	  FOREIGN KEY (employee_ID) REFERENCES Employee(Employee_ID)
);
COMMENT ON TABLE Event_Employee IS 'Junction table: one employee many events, one event many employees';

--DROP TABLE Event_Ticket_Assignment;
CREATE TABLE Event_Ticket_Assignment 
(
	    ticket_id uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL, -- GUID as the primary key
	    attendee_id INT,                               
	    event_id INT,                                
	    purchase_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),                          
	    expiry_date TIMESTAMPTZ NULL,                             
	    Price MONEY NULL,
	    ticket_type VARCHAR(50) NULL,
		FOREIGN KEY (attendee_id) REFERENCES Attendee(attendee_id),
		FOREIGN KEY (event_id) REFERENCES Event(event_id)
);
COMMENT ON TABLE Event_Ticket_Assignment IS 'Junction table: one attendee many events, one event many attendees';	


-- DROP TABLE IF EXISTS public.role_permissions;
CREATE TABLE IF NOT EXISTS public.role_permissions
(
    app_id character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    permission character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (app_id, role, permission),
    CONSTRAINT role_permissions_role_fkey FOREIGN KEY (app_id, role)
        REFERENCES public.roles (app_id, role) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;