/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /3sfGVzJo/s3sc6NpvtODsYKEh/fFiA/U7Hgng/HTEmg/QnHAwdyvpgO6l4vvwuL3sH5jM/iNlmvqHxVe0P4sg==
 */

/* eslint-disable */
// tslint:disable

interface Attendee {
  attendee_id: number & {readonly __brand?: 'attendee_attendee_id'}
  email: string
  first_name: string
  last_name: string
  phone: (string) | null
}
export default Attendee;

interface Attendee_InsertParameters {
  attendee_id: number & {readonly __brand?: 'attendee_attendee_id'}
  email: string
  first_name: string
  last_name: string
  phone?: (string) | null
}
export type {Attendee_InsertParameters}
