/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7NPdpZ+LBmPa1sCLaIgktgtesNQ+ycLyrT+lTLr0xMXCSTaH9j3pDSajCpG/KhBE5yP2FOq840Ovmfh4pkm7Xw==
 */

/* eslint-disable */
// tslint:disable

import Organization from './organization'

interface Employee {
  email: string
  employee_id: number & {readonly __brand?: 'employee_employee_id'}
  first_name: string
  job_title: string
  last_name: string
  organization_id: Organization['organization_id']
}
export default Employee;

interface Employee_InsertParameters {
  email: string
  employee_id: number & {readonly __brand?: 'employee_employee_id'}
  first_name: string
  job_title: string
  last_name: string
  organization_id: Organization['organization_id']
}
export type {Employee_InsertParameters}
