/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VULjt98rI2fNUEQoWam9pDLrx2sh8u1x3sCE+jvx8onBGlEUDwdJXBa6dNKZRcRddLHTFohj9i4INX6cgzjjpA==
 */

/* eslint-disable */
// tslint:disable

import Attendee from './attendee'
import Event from './event'

interface EventTicketAssignment {
  attendee_id: (Attendee['attendee_id']) | null
  event_id: (Event['event_id']) | null
  expiry_date: (Date) | null
  price: (string) | null
  /**
   * @default now()
   */
  purchase_date: Date
  /**
   * @default uuid_generate_v4()
   */
  ticket_id: string & {readonly __brand?: 'event_ticket_assignment_ticket_id'}
  ticket_type: (string) | null
}
export default EventTicketAssignment;

interface EventTicketAssignment_InsertParameters {
  attendee_id?: (Attendee['attendee_id']) | null
  event_id?: (Event['event_id']) | null
  expiry_date?: (Date) | null
  price?: (string) | null
  /**
   * @default now()
   */
  purchase_date?: Date
  /**
   * @default uuid_generate_v4()
   */
  ticket_id?: string & {readonly __brand?: 'event_ticket_assignment_ticket_id'}
  ticket_type?: (string) | null
}
export type {EventTicketAssignment_InsertParameters}
