/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: NPpe71QVImqrJnVVu/CcCNnrSM/9WusbSvtEzDmP1/eKWpa8LaMQQ6+A258ADwKdLyeOTJ6syAdUq1CG6tM6Fw==
 */

/* eslint-disable */
// tslint:disable

import Partner from './partner'

interface EventPartner {
  event_id: number & {readonly __brand?: 'event_partner_event_id'}
  partner_id: Partner['partner_id']
  role: string
}
export default EventPartner;

interface EventPartner_InsertParameters {
  event_id: number & {readonly __brand?: 'event_partner_event_id'}
  partner_id: Partner['partner_id']
  role: string
}
export type {EventPartner_InsertParameters}
