/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: R5QdYYnNRUSovtrJWLS+xwi+t4SF6mCT+EFJCXBLZcJdum1rKMBelswfQvLpIhY2FgrVjENeJGm+YrPKT7WUYQ==
 */

/* eslint-disable */
// tslint:disable

import Event from './event'

interface EventTickets {
  event_id: Event['event_id']
  price: (string) | null
  /**
   * @default uuid_generate_v4()
   */
  ticket_id: string & {readonly __brand?: 'event_tickets_ticket_id'}
  ticket_type: (string) | null
}
export default EventTickets;

interface EventTickets_InsertParameters {
  event_id: Event['event_id']
  price?: (string) | null
  /**
   * @default uuid_generate_v4()
   */
  ticket_id?: string & {readonly __brand?: 'event_tickets_ticket_id'}
  ticket_type?: (string) | null
}
export type {EventTickets_InsertParameters}
