/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JYoG5DaelmcS/qTSLa//nEaSbiVabiUcRnnfYcExhaPbOfBf6VlCfPnFRdjnWttQWJc4QY+d5mp4XfbLNOYLKw==
 */

/* eslint-disable */
// tslint:disable

import Employee from './employee'
import Event from './event'

interface EventEmployee {
  deadline: (Date) | null
  employee_id: Employee['employee_id']
  event_id: Event['event_id']
  start_date: (Date) | null
  task: (string) | null
  task_completed: (string) | null
}
export default EventEmployee;

interface EventEmployee_InsertParameters {
  deadline?: (Date) | null
  employee_id: Employee['employee_id']
  event_id: Event['event_id']
  start_date?: (Date) | null
  task?: (string) | null
  task_completed?: (string) | null
}
export type {EventEmployee_InsertParameters}
