/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wTCZxNz3+xMy34b9I4++K7/mugw5UfFLuyywLcB3WqnP6/CdKsahYqC16biMpsV0Il+lytGPskmEe2bXIA98qQ==
 */

/* eslint-disable */
// tslint:disable

interface EventType {
  event_type_id: number & {readonly __brand?: 'event_type_event_type_id'}
  event_type_name: (string) | null
}
export default EventType;

interface EventType_InsertParameters {
  event_type_id: number & {readonly __brand?: 'event_type_event_type_id'}
  event_type_name?: (string) | null
}
export type {EventType_InsertParameters}
