/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UijOrQg/jo6zeII86Gw07hsF2rFdHTn9tkFX3yR++zQAiTE/loE245oHHfC4pLIR4tDeIdgzPiUrLm1UCGsS8A==
 */

/* eslint-disable */
// tslint:disable

interface Organization {
  contact_person: (string) | null
  email: string
  name: string
  organization_id: number & {readonly __brand?: 'organization_organization_id'}
  phone: (string) | null
}
export default Organization;

interface Organization_InsertParameters {
  contact_person?: (string) | null
  email: string
  name: string
  organization_id: number & {readonly __brand?: 'organization_organization_id'}
  phone?: (string) | null
}
export type {Organization_InsertParameters}
