/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 3BAfjWUiih2/YVOTl2+HkBiUS2PVz0AQ2YWAA1AZ8m2EniY3lNLrtkpbdYJJi0dlDPfsOPa0y1+gd79RnqrU1Q==
 */

/* eslint-disable */
// tslint:disable

interface Partner {
  email: string
  name: string
  partner_id: number & {readonly __brand?: 'partner_partner_id'}
  phone: (string) | null
}
export default Partner;

interface Partner_InsertParameters {
  email: string
  name: string
  partner_id: number & {readonly __brand?: 'partner_partner_id'}
  phone?: (string) | null
}
export type {Partner_InsertParameters}
