/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CzA2ZX5+RZ0X2f6OqMXYVOpWYyBmQVqGVXm/DlBJzeeAsr46NcBT4fcXiQyNhMYLI6Y7tHkc50k6x9m3qndvXw==
 */

/* eslint-disable */
// tslint:disable

interface Venue {
  address_line: (string) | null
  capacity: number
  city: (string) | null
  country: (string) | null
  onlineflag: (string) | null
  postal_code: (string) | null
  state: (string) | null
  venue_id: number & {readonly __brand?: 'venue_venue_id'}
}
export default Venue;

interface Venue_InsertParameters {
  address_line?: (string) | null
  capacity: number
  city?: (string) | null
  country?: (string) | null
  onlineflag?: (string) | null
  postal_code?: (string) | null
  state?: (string) | null
  venue_id: number & {readonly __brand?: 'venue_venue_id'}
}
export type {Venue_InsertParameters}
