/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tQG6PzB6CDiO9wSfX2OkSnugcoXMVyR9de3vc7msw48bqKZm3P3h5iZtZ1BFAs0kbHwUCIKkcPruF19/TBq73w==
 */

/* eslint-disable */
// tslint:disable

import AppIdToUserId from './app_id_to_user_id'
import Tenants from './tenants'

interface AllAuthRecipeUsers {
  /**
   * @default 'public'::character varying
   */
  app_id: AppIdToUserId['app_id']
  /**
   * @default false
   */
  is_linked_or_is_a_primary_user: boolean
  primary_or_recipe_user_id: AppIdToUserId['user_id']
  primary_or_recipe_user_time_joined: number
  recipe_id: string
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export default AllAuthRecipeUsers;

interface AllAuthRecipeUsers_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AppIdToUserId['app_id']
  /**
   * @default false
   */
  is_linked_or_is_a_primary_user?: boolean
  primary_or_recipe_user_id: AppIdToUserId['user_id']
  primary_or_recipe_user_time_joined: number
  recipe_id: string
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export type {AllAuthRecipeUsers_InsertParameters}
