/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /QzBsmyLmLdpuRR+0lJqty9nyqFlTw/q7tqD8IoDkQ9kskn6ZjS1Bx9H35tPHVZ0/JNt4XtsmqhculPLqDPznA==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface AppIdToUserId {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  /**
   * @default false
   */
  is_linked_or_is_a_primary_user: boolean
  primary_or_recipe_user_id: string
  recipe_id: string
  user_id: string & {readonly __brand?: 'app_id_to_user_id_user_id'}
}
export default AppIdToUserId;

interface AppIdToUserId_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  /**
   * @default false
   */
  is_linked_or_is_a_primary_user?: boolean
  primary_or_recipe_user_id: string
  recipe_id: string
  user_id: string & {readonly __brand?: 'app_id_to_user_id_user_id'}
}
export type {AppIdToUserId_InsertParameters}
