/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xsuJOmYKU2MqST+LcVTLRyl89S10wNyCKkiMFi6eM2MVFVbMih1qXzOhIezhmXTygXhh1K0CHR0y3wF133/Gew==
 */

/* eslint-disable */
// tslint:disable

interface Apps {
  /**
   * @default 'public'::character varying
   */
  app_id: string & {readonly __brand?: 'apps_app_id'}
  created_at_time: (number) | null
}
export default Apps;

interface Apps_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: string & {readonly __brand?: 'apps_app_id'}
  created_at_time?: (number) | null
}
export type {Apps_InsertParameters}
