/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7PTkE5Ckb/G0Lg3HmIYO4LikZt98wM6br52niyAk4Ulo3CYPEDc8dZg4v/LdChuI+yU0h7RO6OlAqLv5CzNalg==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface BulkImportUsers {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  created_at: number
  error_msg: (string) | null
  id: string & {readonly __brand?: 'bulk_import_users_id'}
  primary_user_id: (string) | null
  raw_data: string
  /**
   * @default 'NEW'::character varying
   */
  status: (string) | null
  updated_at: number
}
export default BulkImportUsers;

interface BulkImportUsers_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  created_at: number
  error_msg?: (string) | null
  id: string & {readonly __brand?: 'bulk_import_users_id'}
  primary_user_id?: (string) | null
  raw_data: string
  /**
   * @default 'NEW'::character varying
   */
  status?: (string) | null
  updated_at: number
}
export type {BulkImportUsers_InsertParameters}
