/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: oYEenrvzaChjXbRZCQgzR7dNTSZnegdIgYGQRR01FZY13r/BizMLpD8g+PGmNLOezSNXYmFFuif8V/6cz0wjGw==
 */

/* eslint-disable */
// tslint:disable

import DashboardUsers from './dashboard_users'

interface DashboardUserSessions {
  /**
   * @default 'public'::character varying
   */
  app_id: DashboardUsers['app_id']
  expiry: number
  session_id: string & {readonly __brand?: 'dashboard_user_sessions_session_id'}
  time_created: number
  user_id: DashboardUsers['user_id']
}
export default DashboardUserSessions;

interface DashboardUserSessions_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: DashboardUsers['app_id']
  expiry: number
  session_id: string & {readonly __brand?: 'dashboard_user_sessions_session_id'}
  time_created: number
  user_id: DashboardUsers['user_id']
}
export type {DashboardUserSessions_InsertParameters}
