/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: t2bOqRotMAELDMwddq1G0kBx6kmaP6tbKkm8hNTZI9XCJ11jdFupiKY5y9c+xWttXgUvlWMUB/PPn+4tFhwqLA==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface DashboardUsers {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  email: string
  password_hash: string
  time_joined: number
  user_id: string & {readonly __brand?: 'dashboard_users_user_id'}
}
export default DashboardUsers;

interface DashboardUsers_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  email: string
  password_hash: string
  time_joined: number
  user_id: string & {readonly __brand?: 'dashboard_users_user_id'}
}
export type {DashboardUsers_InsertParameters}
