/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: cC0l2QwJP/oLg2H/EN4Nz8kLd1jy5TdH6Jq83b5Q256gS2WyriPYEFij8tJHQ93sxTBgCnBLhNFGeKn0H6BJNQ==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface EmailverificationVerifiedEmails {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  email: string & {readonly __brand?: 'emailverification_verified_emails_email'}
  user_id: string & {readonly __brand?: 'emailverification_verified_emails_user_id'}
}
export default EmailverificationVerifiedEmails;

interface EmailverificationVerifiedEmails_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  email: string & {readonly __brand?: 'emailverification_verified_emails_email'}
  user_id: string & {readonly __brand?: 'emailverification_verified_emails_user_id'}
}
export type {EmailverificationVerifiedEmails_InsertParameters}
