/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ty+7WnG0j0yioZsj5bK7ikXRyB3GL4lt3xqYqkdxxPFT2sEtl8/5gJWZwg7zkIUVovombG5ixXVAGcviYSybvw==
 */

/* eslint-disable */
// tslint:disable

import Tenants from './tenants'

interface EmailverificationTokens {
  /**
   * @default 'public'::character varying
   */
  app_id: Tenants['app_id']
  email: string & {readonly __brand?: 'emailverification_tokens_email'}
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
  token: string & {readonly __brand?: 'emailverification_tokens_token'}
  token_expiry: number
  user_id: string & {readonly __brand?: 'emailverification_tokens_user_id'}
}
export default EmailverificationTokens;

interface EmailverificationTokens_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Tenants['app_id']
  email: string & {readonly __brand?: 'emailverification_tokens_email'}
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
  token: string & {readonly __brand?: 'emailverification_tokens_token'}
  token_expiry: number
  user_id: string & {readonly __brand?: 'emailverification_tokens_user_id'}
}
export type {EmailverificationTokens_InsertParameters}
