/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1GWUh0kLDyVU5yc+Ts+TZZbo/D1B8Zyef7X6NSicUfdO11FsGdRlJwTUjFKdok7gJvaQHalwL36//Fbu4idDFw==
 */

/* eslint-disable */
// tslint:disable

import AllAuthRecipeUsers from './all_auth_recipe_users'

interface EmailpasswordUserToTenant {
  /**
   * @default 'public'::character varying
   */
  app_id: AllAuthRecipeUsers['app_id']
  email: string
  /**
   * @default 'public'::character varying
   */
  tenant_id: AllAuthRecipeUsers['tenant_id']
  user_id: AllAuthRecipeUsers['user_id']
}
export default EmailpasswordUserToTenant;

interface EmailpasswordUserToTenant_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AllAuthRecipeUsers['app_id']
  email: string
  /**
   * @default 'public'::character varying
   */
  tenant_id?: AllAuthRecipeUsers['tenant_id']
  user_id: AllAuthRecipeUsers['user_id']
}
export type {EmailpasswordUserToTenant_InsertParameters}
