/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: +41pi+YGSqW0Lr1TrUJUberT9amrP1xs3IoXUPZbAoRZKgeOWbPNqV/mnN1gtPU/qMWVawrkHb9+IIxNIS/SLQ==
 */

/* eslint-disable */
// tslint:disable

import AppIdToUserId from './app_id_to_user_id'

interface EmailpasswordUsers {
  /**
   * @default 'public'::character varying
   */
  app_id: AppIdToUserId['app_id']
  email: string
  password_hash: string
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export default EmailpasswordUsers;

interface EmailpasswordUsers_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AppIdToUserId['app_id']
  email: string
  password_hash: string
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export type {EmailpasswordUsers_InsertParameters}
