/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: L/DF9e0a7rbmo2jmR148LbxVTqFv1GJsIxdlAcjYtDDYo5BaWvERaEU9C2tkXb1K0lz7kX8Obeu4aifCCQJKLw==
 */

/* eslint-disable */
// tslint:disable

import AppIdToUserId from './app_id_to_user_id'

interface EmailpasswordPswdResetTokens {
  /**
   * @default 'public'::character varying
   */
  app_id: AppIdToUserId['app_id']
  email: (string) | null
  token: string & {readonly __brand?: 'emailpassword_pswd_reset_tokens_token'}
  token_expiry: number
  user_id: AppIdToUserId['user_id']
}
export default EmailpasswordPswdResetTokens;

interface EmailpasswordPswdResetTokens_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AppIdToUserId['app_id']
  email?: (string) | null
  token: string & {readonly __brand?: 'emailpassword_pswd_reset_tokens_token'}
  token_expiry: number
  user_id: AppIdToUserId['user_id']
}
export type {EmailpasswordPswdResetTokens_InsertParameters}
