/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: uxSs5k8vbPLUqQ2XZt2a9w1B+fgPBzfkGZMk4lzrb/ObMe3FeFiBefX1AOmCvKFH7VXerILkawUpUI4cb8el9Q==
 */

/* eslint-disable */
// tslint:disable

import AllAuthRecipeUsers, {AllAuthRecipeUsers_InsertParameters} from './all_auth_recipe_users'
import AppIdToUserId, {AppIdToUserId_InsertParameters} from './app_id_to_user_id'
import Apps, {Apps_InsertParameters} from './apps'
import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import BulkImportUsers, {BulkImportUsers_InsertParameters} from './bulk_import_users'
import DashboardUserSessions, {DashboardUserSessions_InsertParameters} from './dashboard_user_sessions'
import DashboardUsers, {DashboardUsers_InsertParameters} from './dashboard_users'
import EmailpasswordPswdResetTokens, {EmailpasswordPswdResetTokens_InsertParameters} from './emailpassword_pswd_reset_tokens'
import EmailpasswordUserToTenant, {EmailpasswordUserToTenant_InsertParameters} from './emailpassword_user_to_tenant'
import EmailpasswordUsers, {EmailpasswordUsers_InsertParameters} from './emailpassword_users'
import EmailverificationTokens, {EmailverificationTokens_InsertParameters} from './emailverification_tokens'
import EmailverificationVerifiedEmails, {EmailverificationVerifiedEmails_InsertParameters} from './emailverification_verified_emails'
import JwtSigningKeys, {JwtSigningKeys_InsertParameters} from './jwt_signing_keys'
import KeyValue, {KeyValue_InsertParameters} from './key_value'
import OauthClients, {OauthClients_InsertParameters} from './oauth_clients'
import OauthLogoutChallenges, {OauthLogoutChallenges_InsertParameters} from './oauth_logout_challenges'
import OauthM2mTokens, {OauthM2mTokens_InsertParameters} from './oauth_m2m_tokens'
import OauthSessions, {OauthSessions_InsertParameters} from './oauth_sessions'
import PasswordlessCodes, {PasswordlessCodes_InsertParameters} from './passwordless_codes'
import PasswordlessDevices, {PasswordlessDevices_InsertParameters} from './passwordless_devices'
import PasswordlessUserToTenant, {PasswordlessUserToTenant_InsertParameters} from './passwordless_user_to_tenant'
import PasswordlessUsers, {PasswordlessUsers_InsertParameters} from './passwordless_users'
import RolePermissions, {RolePermissions_InsertParameters} from './role_permissions'
import Roles, {Roles_InsertParameters} from './roles'
import SamlClaims, {SamlClaims_InsertParameters} from './saml_claims'
import SamlClients, {SamlClients_InsertParameters} from './saml_clients'
import SamlRelayState, {SamlRelayState_InsertParameters} from './saml_relay_state'
import SessionAccessTokenSigningKeys, {SessionAccessTokenSigningKeys_InsertParameters} from './session_access_token_signing_keys'
import SessionInfo, {SessionInfo_InsertParameters} from './session_info'
import TenantConfigs, {TenantConfigs_InsertParameters} from './tenant_configs'
import TenantFirstFactors, {TenantFirstFactors_InsertParameters} from './tenant_first_factors'
import TenantRequiredSecondaryFactors, {TenantRequiredSecondaryFactors_InsertParameters} from './tenant_required_secondary_factors'
import TenantThirdpartyProviderClients, {TenantThirdpartyProviderClients_InsertParameters} from './tenant_thirdparty_provider_clients'
import TenantThirdpartyProviders, {TenantThirdpartyProviders_InsertParameters} from './tenant_thirdparty_providers'
import Tenants, {Tenants_InsertParameters} from './tenants'
import ThirdpartyUserToTenant, {ThirdpartyUserToTenant_InsertParameters} from './thirdparty_user_to_tenant'
import ThirdpartyUsers, {ThirdpartyUsers_InsertParameters} from './thirdparty_users'
import TotpUsedCodes, {TotpUsedCodes_InsertParameters} from './totp_used_codes'
import TotpUserDevices, {TotpUserDevices_InsertParameters} from './totp_user_devices'
import TotpUsers, {TotpUsers_InsertParameters} from './totp_users'
import UserLastActive, {UserLastActive_InsertParameters} from './user_last_active'
import UserMetadata, {UserMetadata_InsertParameters} from './user_metadata'
import UserRoles, {UserRoles_InsertParameters} from './user_roles'
import UseridMapping, {UseridMapping_InsertParameters} from './userid_mapping'
import WebauthnAccountRecoveryTokens, {WebauthnAccountRecoveryTokens_InsertParameters} from './webauthn_account_recovery_tokens'
import WebauthnCredentials, {WebauthnCredentials_InsertParameters} from './webauthn_credentials'
import WebauthnGeneratedOptions, {WebauthnGeneratedOptions_InsertParameters} from './webauthn_generated_options'
import WebauthnUserToTenant, {WebauthnUserToTenant_InsertParameters} from './webauthn_user_to_tenant'
import WebauthnUsers, {WebauthnUsers_InsertParameters} from './webauthn_users'

interface DatabaseSchema {
  all_auth_recipe_users: {record: AllAuthRecipeUsers, insert: AllAuthRecipeUsers_InsertParameters};
  app_id_to_user_id: {record: AppIdToUserId, insert: AppIdToUserId_InsertParameters};
  apps: {record: Apps, insert: Apps_InsertParameters};
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  bulk_import_users: {record: BulkImportUsers, insert: BulkImportUsers_InsertParameters};
  dashboard_user_sessions: {record: DashboardUserSessions, insert: DashboardUserSessions_InsertParameters};
  dashboard_users: {record: DashboardUsers, insert: DashboardUsers_InsertParameters};
  emailpassword_pswd_reset_tokens: {record: EmailpasswordPswdResetTokens, insert: EmailpasswordPswdResetTokens_InsertParameters};
  emailpassword_user_to_tenant: {record: EmailpasswordUserToTenant, insert: EmailpasswordUserToTenant_InsertParameters};
  emailpassword_users: {record: EmailpasswordUsers, insert: EmailpasswordUsers_InsertParameters};
  emailverification_tokens: {record: EmailverificationTokens, insert: EmailverificationTokens_InsertParameters};
  emailverification_verified_emails: {record: EmailverificationVerifiedEmails, insert: EmailverificationVerifiedEmails_InsertParameters};
  jwt_signing_keys: {record: JwtSigningKeys, insert: JwtSigningKeys_InsertParameters};
  key_value: {record: KeyValue, insert: KeyValue_InsertParameters};
  oauth_clients: {record: OauthClients, insert: OauthClients_InsertParameters};
  oauth_logout_challenges: {record: OauthLogoutChallenges, insert: OauthLogoutChallenges_InsertParameters};
  oauth_m2m_tokens: {record: OauthM2mTokens, insert: OauthM2mTokens_InsertParameters};
  oauth_sessions: {record: OauthSessions, insert: OauthSessions_InsertParameters};
  passwordless_codes: {record: PasswordlessCodes, insert: PasswordlessCodes_InsertParameters};
  passwordless_devices: {record: PasswordlessDevices, insert: PasswordlessDevices_InsertParameters};
  passwordless_user_to_tenant: {record: PasswordlessUserToTenant, insert: PasswordlessUserToTenant_InsertParameters};
  passwordless_users: {record: PasswordlessUsers, insert: PasswordlessUsers_InsertParameters};
  role_permissions: {record: RolePermissions, insert: RolePermissions_InsertParameters};
  roles: {record: Roles, insert: Roles_InsertParameters};
  saml_claims: {record: SamlClaims, insert: SamlClaims_InsertParameters};
  saml_clients: {record: SamlClients, insert: SamlClients_InsertParameters};
  saml_relay_state: {record: SamlRelayState, insert: SamlRelayState_InsertParameters};
  session_access_token_signing_keys: {record: SessionAccessTokenSigningKeys, insert: SessionAccessTokenSigningKeys_InsertParameters};
  session_info: {record: SessionInfo, insert: SessionInfo_InsertParameters};
  tenant_configs: {record: TenantConfigs, insert: TenantConfigs_InsertParameters};
  tenant_first_factors: {record: TenantFirstFactors, insert: TenantFirstFactors_InsertParameters};
  tenant_required_secondary_factors: {record: TenantRequiredSecondaryFactors, insert: TenantRequiredSecondaryFactors_InsertParameters};
  tenant_thirdparty_provider_clients: {record: TenantThirdpartyProviderClients, insert: TenantThirdpartyProviderClients_InsertParameters};
  tenant_thirdparty_providers: {record: TenantThirdpartyProviders, insert: TenantThirdpartyProviders_InsertParameters};
  tenants: {record: Tenants, insert: Tenants_InsertParameters};
  thirdparty_user_to_tenant: {record: ThirdpartyUserToTenant, insert: ThirdpartyUserToTenant_InsertParameters};
  thirdparty_users: {record: ThirdpartyUsers, insert: ThirdpartyUsers_InsertParameters};
  totp_used_codes: {record: TotpUsedCodes, insert: TotpUsedCodes_InsertParameters};
  totp_user_devices: {record: TotpUserDevices, insert: TotpUserDevices_InsertParameters};
  totp_users: {record: TotpUsers, insert: TotpUsers_InsertParameters};
  user_last_active: {record: UserLastActive, insert: UserLastActive_InsertParameters};
  user_metadata: {record: UserMetadata, insert: UserMetadata_InsertParameters};
  user_roles: {record: UserRoles, insert: UserRoles_InsertParameters};
  userid_mapping: {record: UseridMapping, insert: UseridMapping_InsertParameters};
  webauthn_account_recovery_tokens: {record: WebauthnAccountRecoveryTokens, insert: WebauthnAccountRecoveryTokens_InsertParameters};
  webauthn_credentials: {record: WebauthnCredentials, insert: WebauthnCredentials_InsertParameters};
  webauthn_generated_options: {record: WebauthnGeneratedOptions, insert: WebauthnGeneratedOptions_InsertParameters};
  webauthn_user_to_tenant: {record: WebauthnUserToTenant, insert: WebauthnUserToTenant_InsertParameters};
  webauthn_users: {record: WebauthnUsers, insert: WebauthnUsers_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AllAuthRecipeUsers,
  AllAuthRecipeUsers_InsertParameters,
  AppIdToUserId,
  AppIdToUserId_InsertParameters,
  Apps,
  Apps_InsertParameters,
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  BulkImportUsers,
  BulkImportUsers_InsertParameters,
  DashboardUserSessions,
  DashboardUserSessions_InsertParameters,
  DashboardUsers,
  DashboardUsers_InsertParameters,
  EmailpasswordPswdResetTokens,
  EmailpasswordPswdResetTokens_InsertParameters,
  EmailpasswordUserToTenant,
  EmailpasswordUserToTenant_InsertParameters,
  EmailpasswordUsers,
  EmailpasswordUsers_InsertParameters,
  EmailverificationTokens,
  EmailverificationTokens_InsertParameters,
  EmailverificationVerifiedEmails,
  EmailverificationVerifiedEmails_InsertParameters,
  JwtSigningKeys,
  JwtSigningKeys_InsertParameters,
  KeyValue,
  KeyValue_InsertParameters,
  OauthClients,
  OauthClients_InsertParameters,
  OauthLogoutChallenges,
  OauthLogoutChallenges_InsertParameters,
  OauthM2mTokens,
  OauthM2mTokens_InsertParameters,
  OauthSessions,
  OauthSessions_InsertParameters,
  PasswordlessCodes,
  PasswordlessCodes_InsertParameters,
  PasswordlessDevices,
  PasswordlessDevices_InsertParameters,
  PasswordlessUserToTenant,
  PasswordlessUserToTenant_InsertParameters,
  PasswordlessUsers,
  PasswordlessUsers_InsertParameters,
  RolePermissions,
  RolePermissions_InsertParameters,
  Roles,
  Roles_InsertParameters,
  SamlClaims,
  SamlClaims_InsertParameters,
  SamlClients,
  SamlClients_InsertParameters,
  SamlRelayState,
  SamlRelayState_InsertParameters,
  SessionAccessTokenSigningKeys,
  SessionAccessTokenSigningKeys_InsertParameters,
  SessionInfo,
  SessionInfo_InsertParameters,
  TenantConfigs,
  TenantConfigs_InsertParameters,
  TenantFirstFactors,
  TenantFirstFactors_InsertParameters,
  TenantRequiredSecondaryFactors,
  TenantRequiredSecondaryFactors_InsertParameters,
  TenantThirdpartyProviderClients,
  TenantThirdpartyProviderClients_InsertParameters,
  TenantThirdpartyProviders,
  TenantThirdpartyProviders_InsertParameters,
  Tenants,
  Tenants_InsertParameters,
  ThirdpartyUserToTenant,
  ThirdpartyUserToTenant_InsertParameters,
  ThirdpartyUsers,
  ThirdpartyUsers_InsertParameters,
  TotpUsedCodes,
  TotpUsedCodes_InsertParameters,
  TotpUserDevices,
  TotpUserDevices_InsertParameters,
  TotpUsers,
  TotpUsers_InsertParameters,
  UserLastActive,
  UserLastActive_InsertParameters,
  UserMetadata,
  UserMetadata_InsertParameters,
  UserRoles,
  UserRoles_InsertParameters,
  UseridMapping,
  UseridMapping_InsertParameters,
  WebauthnAccountRecoveryTokens,
  WebauthnAccountRecoveryTokens_InsertParameters,
  WebauthnCredentials,
  WebauthnCredentials_InsertParameters,
  WebauthnGeneratedOptions,
  WebauthnGeneratedOptions_InsertParameters,
  WebauthnUserToTenant,
  WebauthnUserToTenant_InsertParameters,
  WebauthnUsers,
  WebauthnUsers_InsertParameters,
}
