/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZD/kfr0HBi7OUM8Rv5D6FI8tytZFdiXpKJ1DXAqhEop/DKSuIEWkF4Q9mT7jGDrJJ0Rlychh2XkvvKwMxB9DTg==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface JwtSigningKeys {
  algorithm: string
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  created_at: (number) | null
  key_id: string & {readonly __brand?: 'jwt_signing_keys_key_id'}
  key_string: string
}
export default JwtSigningKeys;

interface JwtSigningKeys_InsertParameters {
  algorithm: string
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  created_at?: (number) | null
  key_id: string & {readonly __brand?: 'jwt_signing_keys_key_id'}
  key_string: string
}
export type {JwtSigningKeys_InsertParameters}
