/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: NTykUSbs3jAr6s4pNfI3GPlHqz7WIkBVsIa7EUSncMJkV3seaIPJrv9D4IOV7p4uqlkU+aG/E9gO3d6nDirP7A==
 */

/* eslint-disable */
// tslint:disable

import Tenants from './tenants'

interface KeyValue {
  /**
   * @default 'public'::character varying
   */
  app_id: Tenants['app_id']
  created_at_time: (number) | null
  name: string & {readonly __brand?: 'key_value_name'}
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
  value: (string) | null
}
export default KeyValue;

interface KeyValue_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Tenants['app_id']
  created_at_time?: (number) | null
  name: string & {readonly __brand?: 'key_value_name'}
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
  value?: (string) | null
}
export type {KeyValue_InsertParameters}
