/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Z7zM1nsvQiKj0YNk2dask2nBiIhahOIl2GarXaLA/NPoNrpqJIFFi3VA1PUg/NYabhdMvhSujZuwB0UtjEw6HQ==
 */

/* eslint-disable */
// tslint:disable

import OauthClients from './oauth_clients'

interface OauthM2mTokens {
  /**
   * @default 'public'::character varying
   */
  app_id: OauthClients['app_id']
  client_id: OauthClients['client_id']
  exp: number
  iat: number & {readonly __brand?: 'oauth_m2m_tokens_iat'}
}
export default OauthM2mTokens;

interface OauthM2mTokens_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: OauthClients['app_id']
  client_id: OauthClients['client_id']
  exp: number
  iat: number & {readonly __brand?: 'oauth_m2m_tokens_iat'}
}
export type {OauthM2mTokens_InsertParameters}
