/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 3sjqCvV9X7DgubUc8iUDVFM48lo8cPmkMN+FODD5ZjOMuzEyFWrHnWNybyZRQZJeHaD5hveM1ffe8oUm5pfMPA==
 */

/* eslint-disable */
// tslint:disable

import OauthClients from './oauth_clients'

interface OauthLogoutChallenges {
  /**
   * @default 'public'::character varying
   */
  app_id: OauthClients['app_id']
  challenge: string & {readonly __brand?: 'oauth_logout_challenges_challenge'}
  client_id: OauthClients['client_id']
  post_logout_redirect_uri: (string) | null
  session_handle: (string) | null
  state: (string) | null
  time_created: number
}
export default OauthLogoutChallenges;

interface OauthLogoutChallenges_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: OauthClients['app_id']
  challenge: string & {readonly __brand?: 'oauth_logout_challenges_challenge'}
  client_id: OauthClients['client_id']
  post_logout_redirect_uri?: (string) | null
  session_handle?: (string) | null
  state?: (string) | null
  time_created: number
}
export type {OauthLogoutChallenges_InsertParameters}
