/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8YMIwvcTgNfUfpEh9ghj7VCdLfxrdjrjV4UZSgDpRPw3PwY7gnXp0hE+AWVmi3ckwxyeqPj35fxHDZB6ILd2Cw==
 */

/* eslint-disable */
// tslint:disable

import OauthClients from './oauth_clients'

interface OauthSessions {
  /**
   * @default 'public'::character varying
   */
  app_id: (OauthClients['app_id']) | null
  client_id: OauthClients['client_id']
  exp: number
  external_refresh_token: (string) | null
  gid: string & {readonly __brand?: 'oauth_sessions_gid'}
  internal_refresh_token: (string) | null
  jti: string
  session_handle: (string) | null
}
export default OauthSessions;

interface OauthSessions_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: (OauthClients['app_id']) | null
  client_id: OauthClients['client_id']
  exp: number
  external_refresh_token?: (string) | null
  gid: string & {readonly __brand?: 'oauth_sessions_gid'}
  internal_refresh_token?: (string) | null
  jti: string
  session_handle?: (string) | null
}
export type {OauthSessions_InsertParameters}
