/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: OhBCQoR2Vx9tACJ2GqiiGJXGZF0HFE2WnFPT0O5nAshVLalW4QEDWA2UH5K1jdFMgxs3AD66OwH0TET64VSWWg==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface OauthClients {
  app_id: Apps['app_id']
  client_id: string & {readonly __brand?: 'oauth_clients_client_id'}
  client_secret: (string) | null
  enable_refresh_token_rotation: boolean
  is_client_credentials_only: boolean
}
export default OauthClients;

interface OauthClients_InsertParameters {
  app_id: Apps['app_id']
  client_id: string & {readonly __brand?: 'oauth_clients_client_id'}
  client_secret?: (string) | null
  enable_refresh_token_rotation: boolean
  is_client_credentials_only: boolean
}
export type {OauthClients_InsertParameters}
