/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: nNt9OTfi6yIz8vP5B1gShipTM4sgpVg4TXIA4W3pkU7QLEyrkh83yEQMkP+WJtttkPEmWddUWdNedJTTFQFKLg==
 */

/* eslint-disable */
// tslint:disable

import Tenants from './tenants'

interface PasswordlessDevices {
  /**
   * @default 'public'::character varying
   */
  app_id: Tenants['app_id']
  device_id_hash: string & {readonly __brand?: 'passwordless_devices_device_id_hash'}
  email: (string) | null
  failed_attempts: number
  link_code_salt: string
  phone_number: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
}
export default PasswordlessDevices;

interface PasswordlessDevices_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Tenants['app_id']
  device_id_hash: string & {readonly __brand?: 'passwordless_devices_device_id_hash'}
  email?: (string) | null
  failed_attempts: number
  link_code_salt: string
  phone_number?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
}
export type {PasswordlessDevices_InsertParameters}
