/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JQaxPxBfBg/gpGgSRXpiPAJCgs7qCEMzS65iRa3QTHFhmtQjz7jrZvPT0JAs+/CCkUGnQ/UdZo3gL4Ua6tMT5A==
 */

/* eslint-disable */
// tslint:disable

import AllAuthRecipeUsers from './all_auth_recipe_users'

interface PasswordlessUserToTenant {
  /**
   * @default 'public'::character varying
   */
  app_id: AllAuthRecipeUsers['app_id']
  email: (string) | null
  phone_number: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: AllAuthRecipeUsers['tenant_id']
  user_id: AllAuthRecipeUsers['user_id']
}
export default PasswordlessUserToTenant;

interface PasswordlessUserToTenant_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AllAuthRecipeUsers['app_id']
  email?: (string) | null
  phone_number?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: AllAuthRecipeUsers['tenant_id']
  user_id: AllAuthRecipeUsers['user_id']
}
export type {PasswordlessUserToTenant_InsertParameters}
