/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EtQXX+QvtiBYSN6Na3X6qSG2/e2izGcgBtGUgHxUXtPmHjbXyo2fBJVXWW4mk4gcYAL1gFE6VsqWSUMoEcSmzA==
 */

/* eslint-disable */
// tslint:disable

import AppIdToUserId from './app_id_to_user_id'

interface PasswordlessUsers {
  /**
   * @default 'public'::character varying
   */
  app_id: AppIdToUserId['app_id']
  email: (string) | null
  phone_number: (string) | null
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export default PasswordlessUsers;

interface PasswordlessUsers_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AppIdToUserId['app_id']
  email?: (string) | null
  phone_number?: (string) | null
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export type {PasswordlessUsers_InsertParameters}
