/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Z3loNkb5NEZTJHNXUV/R34RHwftSTUk9QbgyJumlk0zaNPoqXAX2w6C2fByhN1pVtY8gsRvWJfAu0uZ1y6TL6w==
 */

/* eslint-disable */
// tslint:disable

import PasswordlessDevices from './passwordless_devices'

interface PasswordlessCodes {
  /**
   * @default 'public'::character varying
   */
  app_id: PasswordlessDevices['app_id']
  code_id: string & {readonly __brand?: 'passwordless_codes_code_id'}
  created_at: number
  device_id_hash: PasswordlessDevices['device_id_hash']
  link_code_hash: string
  /**
   * @default 'public'::character varying
   */
  tenant_id: PasswordlessDevices['tenant_id']
}
export default PasswordlessCodes;

interface PasswordlessCodes_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: PasswordlessDevices['app_id']
  code_id: string & {readonly __brand?: 'passwordless_codes_code_id'}
  created_at: number
  device_id_hash: PasswordlessDevices['device_id_hash']
  link_code_hash: string
  /**
   * @default 'public'::character varying
   */
  tenant_id?: PasswordlessDevices['tenant_id']
}
export type {PasswordlessCodes_InsertParameters}
