/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1rqOaGshSRkWZWlVjB4c505akgX96KHlkVD0HlrGZdRPeaWEu+sLm5zGHo5heDp8vfv4MCiL05grtc8j+Onk1Q==
 */

/* eslint-disable */
// tslint:disable

import Roles from './roles'

interface RolePermissions {
  /**
   * @default 'public'::character varying
   */
  app_id: Roles['app_id']
  permission: string & {readonly __brand?: 'role_permissions_permission'}
  role: Roles['role']
}
export default RolePermissions;

interface RolePermissions_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Roles['app_id']
  permission: string & {readonly __brand?: 'role_permissions_permission'}
  role: Roles['role']
}
export type {RolePermissions_InsertParameters}
