/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: qLNnTGIcJwIzufmgVy4F7KSYQL+DoTLXYm/nwyVfgjglZVf4Domq77ANa6uH7Z7mygsfBiJk2unxtqBmq5imRw==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface Roles {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  role: string & {readonly __brand?: 'roles_role'}
}
export default Roles;

interface Roles_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  role: string & {readonly __brand?: 'roles_role'}
}
export type {Roles_InsertParameters}
