/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xMoIDOc2BrhzgyI1h3Y1s38dA3cqQd4K4UmKAlbadGrfaCJxF2IcPXzuCvaVop1hY/JewI6HFZ2QHJgZ6TUIVQ==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'
import Tenants from './tenants'

interface SamlClaims {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  claims: string
  client_id: string
  code: string & {readonly __brand?: 'saml_claims_code'}
  created_at: number
  expires_at: number
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
}
export default SamlClaims;

interface SamlClaims_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  claims: string
  client_id: string
  code: string & {readonly __brand?: 'saml_claims_code'}
  created_at: number
  expires_at: number
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
}
export type {SamlClaims_InsertParameters}
