/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5RDHKwM7uGcVepcLcUZaLlvJ2PFZ6hBru2uBsGd4xApOmNQ3YTSmrkOWa8e3KoFq90H+2/VRGKsa21pni1aXwA==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'
import Tenants from './tenants'

interface SamlClients {
  /**
   * @default false
   */
  allow_idp_initiated_login: boolean
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  client_id: string & {readonly __brand?: 'saml_clients_client_id'}
  client_secret: (string) | null
  created_at: number
  default_redirect_uri: string
  /**
   * @default false
   */
  enable_request_signing: boolean
  idp_entity_id: string
  idp_signing_certificate: string
  redirect_uris: string
  sso_login_url: string
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
  updated_at: number
}
export default SamlClients;

interface SamlClients_InsertParameters {
  /**
   * @default false
   */
  allow_idp_initiated_login?: boolean
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  client_id: string & {readonly __brand?: 'saml_clients_client_id'}
  client_secret?: (string) | null
  created_at: number
  default_redirect_uri: string
  /**
   * @default false
   */
  enable_request_signing?: boolean
  idp_entity_id: string
  idp_signing_certificate: string
  redirect_uris: string
  sso_login_url: string
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
  updated_at: number
}
export type {SamlClients_InsertParameters}
