/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: LjOV3XdXkNjb3ukF29dsp/V+SscSpHk7JFbz8nqNJEWmCMk9SfEppHqmZ2es+8EQZoIXR4j3b8uYt1gwESoLbg==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'
import Tenants from './tenants'

interface SamlRelayState {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  client_id: string
  created_at: number
  expires_at: number
  redirect_uri: string
  relay_state: string & {readonly __brand?: 'saml_relay_state_relay_state'}
  state: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
}
export default SamlRelayState;

interface SamlRelayState_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  client_id: string
  created_at: number
  expires_at: number
  redirect_uri: string
  relay_state: string & {readonly __brand?: 'saml_relay_state_relay_state'}
  state?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
}
export type {SamlRelayState_InsertParameters}
