/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tGFdCSJuI96l0rpMJa+CCuTyhPk38941qdml4HCaa8OyWFLcizbBTmL5CXrYAx9nbkp+sMPtTPMMXoRhUfQEnA==
 */

/* eslint-disable */
// tslint:disable

import Tenants from './tenants'

interface SessionInfo {
  /**
   * @default 'public'::character varying
   */
  app_id: Tenants['app_id']
  created_at_time: number
  expires_at: number
  jwt_user_payload: (string) | null
  refresh_token_hash_2: string
  session_data: (string) | null
  session_handle: string & {readonly __brand?: 'session_info_session_handle'}
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
  use_static_key: boolean
  user_id: string
}
export default SessionInfo;

interface SessionInfo_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Tenants['app_id']
  created_at_time: number
  expires_at: number
  jwt_user_payload?: (string) | null
  refresh_token_hash_2: string
  session_data?: (string) | null
  session_handle: string & {readonly __brand?: 'session_info_session_handle'}
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
  use_static_key: boolean
  user_id: string
}
export type {SessionInfo_InsertParameters}
