/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xujDNbrQ/0CunSuyLAo9WV2rzhkju4T3cjtykW0kE6hdnP0tR0BjYvVUHXm/bLyhUMTlB69EQ3qcWgvVEyT2Ig==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface SessionAccessTokenSigningKeys {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  created_at_time: number & {readonly __brand?: 'session_access_token_signing_keys_created_at_time'}
  value: (string) | null
}
export default SessionAccessTokenSigningKeys;

interface SessionAccessTokenSigningKeys_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  created_at_time: number & {readonly __brand?: 'session_access_token_signing_keys_created_at_time'}
  value?: (string) | null
}
export type {SessionAccessTokenSigningKeys_InsertParameters}
