/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: a/BdL7m8khFt02IQKKRjxWqLKUbocABnKpI7OsFSicpdIXlKT/YJC1V/Fo2sLc4R1Ob0k51fvzwTMdVBwSSZKQ==
 */

/* eslint-disable */
// tslint:disable

import TenantConfigs from './tenant_configs'

interface TenantRequiredSecondaryFactors {
  /**
   * @default 'public'::character varying
   */
  app_id: TenantConfigs['app_id']
  /**
   * @default ''::character varying
   */
  connection_uri_domain: TenantConfigs['connection_uri_domain']
  factor_id: string & {readonly __brand?: 'tenant_required_secondary_factors_factor_id'}
  /**
   * @default 'public'::character varying
   */
  tenant_id: TenantConfigs['tenant_id']
}
export default TenantRequiredSecondaryFactors;

interface TenantRequiredSecondaryFactors_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: TenantConfigs['app_id']
  /**
   * @default ''::character varying
   */
  connection_uri_domain?: TenantConfigs['connection_uri_domain']
  factor_id: string & {readonly __brand?: 'tenant_required_secondary_factors_factor_id'}
  /**
   * @default 'public'::character varying
   */
  tenant_id?: TenantConfigs['tenant_id']
}
export type {TenantRequiredSecondaryFactors_InsertParameters}
