/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: I0SiHUgdAtnRFjef6fOHZH6lbD4upDWHo8EgdqR2dKhUJZc1PxLrBD43otulISO0emJluUhOlLkw8RupD781cQ==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface Tenants {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  created_at_time: (number) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string & {readonly __brand?: 'tenants_tenant_id'}
}
export default Tenants;

interface Tenants_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  created_at_time?: (number) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string & {readonly __brand?: 'tenants_tenant_id'}
}
export type {Tenants_InsertParameters}
