/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Uwk/LLhLCwGTiaDgskQuyYuMzdDBikPf4hezZQ5VfDsAT+qLJxMslOtueXRYf/NJmIxZ9YbbINpMTqwsPpREIw==
 */

/* eslint-disable */
// tslint:disable

import TenantConfigs from './tenant_configs'

interface TenantThirdpartyProviders {
  /**
   * @default 'public'::character varying
   */
  app_id: TenantConfigs['app_id']
  authorization_endpoint: (string) | null
  authorization_endpoint_query_params: (string) | null
  /**
   * @default ''::character varying
   */
  connection_uri_domain: TenantConfigs['connection_uri_domain']
  jwks_uri: (string) | null
  name: (string) | null
  oidc_discovery_endpoint: (string) | null
  require_email: (boolean) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: TenantConfigs['tenant_id']
  third_party_id: string & {readonly __brand?: 'tenant_thirdparty_providers_third_party_id'}
  token_endpoint: (string) | null
  token_endpoint_body_params: (string) | null
  user_info_endpoint: (string) | null
  user_info_endpoint_headers: (string) | null
  user_info_endpoint_query_params: (string) | null
  user_info_map_from_id_token_payload_email: (string) | null
  user_info_map_from_id_token_payload_email_verified: (string) | null
  user_info_map_from_id_token_payload_user_id: (string) | null
  user_info_map_from_user_info_endpoint_email: (string) | null
  user_info_map_from_user_info_endpoint_email_verified: (string) | null
  user_info_map_from_user_info_endpoint_user_id: (string) | null
}
export default TenantThirdpartyProviders;

interface TenantThirdpartyProviders_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: TenantConfigs['app_id']
  authorization_endpoint?: (string) | null
  authorization_endpoint_query_params?: (string) | null
  /**
   * @default ''::character varying
   */
  connection_uri_domain?: TenantConfigs['connection_uri_domain']
  jwks_uri?: (string) | null
  name?: (string) | null
  oidc_discovery_endpoint?: (string) | null
  require_email?: (boolean) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: TenantConfigs['tenant_id']
  third_party_id: string & {readonly __brand?: 'tenant_thirdparty_providers_third_party_id'}
  token_endpoint?: (string) | null
  token_endpoint_body_params?: (string) | null
  user_info_endpoint?: (string) | null
  user_info_endpoint_headers?: (string) | null
  user_info_endpoint_query_params?: (string) | null
  user_info_map_from_id_token_payload_email?: (string) | null
  user_info_map_from_id_token_payload_email_verified?: (string) | null
  user_info_map_from_id_token_payload_user_id?: (string) | null
  user_info_map_from_user_info_endpoint_email?: (string) | null
  user_info_map_from_user_info_endpoint_email_verified?: (string) | null
  user_info_map_from_user_info_endpoint_user_id?: (string) | null
}
export type {TenantThirdpartyProviders_InsertParameters}
