/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: l7CCwPIGfJtuicHmVxZSVP/O4x3XBVfkY+sydRVSxywHUh0VrkURcQ7YdXE0y+//so7Eer4K8FdfTkCPkTZAnw==
 */

/* eslint-disable */
// tslint:disable

interface TenantConfigs {
  /**
   * @default 'public'::character varying
   */
  app_id: string & {readonly __brand?: 'tenant_configs_app_id'}
  /**
   * @default ''::character varying
   */
  connection_uri_domain: string & {readonly __brand?: 'tenant_configs_connection_uri_domain'}
  core_config: (string) | null
  email_password_enabled: (boolean) | null
  is_first_factors_null: (boolean) | null
  passwordless_enabled: (boolean) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string & {readonly __brand?: 'tenant_configs_tenant_id'}
  third_party_enabled: (boolean) | null
}
export default TenantConfigs;

interface TenantConfigs_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: string & {readonly __brand?: 'tenant_configs_app_id'}
  /**
   * @default ''::character varying
   */
  connection_uri_domain?: string & {readonly __brand?: 'tenant_configs_connection_uri_domain'}
  core_config?: (string) | null
  email_password_enabled?: (boolean) | null
  is_first_factors_null?: (boolean) | null
  passwordless_enabled?: (boolean) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string & {readonly __brand?: 'tenant_configs_tenant_id'}
  third_party_enabled?: (boolean) | null
}
export type {TenantConfigs_InsertParameters}
