/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0750zFWS6HB/i8U6aJ64J2MZaRZxqg4+NsXO+1jKzxaQ6dVcGblbGAooqA3nALMIqYfJ9EvTnCyDYOyDmGDDVw==
 */

/* eslint-disable */
// tslint:disable

import TenantConfigs from './tenant_configs'

interface TenantFirstFactors {
  /**
   * @default 'public'::character varying
   */
  app_id: TenantConfigs['app_id']
  /**
   * @default ''::character varying
   */
  connection_uri_domain: TenantConfigs['connection_uri_domain']
  factor_id: string & {readonly __brand?: 'tenant_first_factors_factor_id'}
  /**
   * @default 'public'::character varying
   */
  tenant_id: TenantConfigs['tenant_id']
}
export default TenantFirstFactors;

interface TenantFirstFactors_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: TenantConfigs['app_id']
  /**
   * @default ''::character varying
   */
  connection_uri_domain?: TenantConfigs['connection_uri_domain']
  factor_id: string & {readonly __brand?: 'tenant_first_factors_factor_id'}
  /**
   * @default 'public'::character varying
   */
  tenant_id?: TenantConfigs['tenant_id']
}
export type {TenantFirstFactors_InsertParameters}
