/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FFqH1GZpFkLkADnLIv5VL2kOfiIj6W4z72ZZpbWk0dQ2BHfdR7Blx4v4VK0CSYysu75/FgSB2+i1M4LT4HyLKQ==
 */

/* eslint-disable */
// tslint:disable

import TenantThirdpartyProviders from './tenant_thirdparty_providers'

interface TenantThirdpartyProviderClients {
  additional_config: (string) | null
  /**
   * @default 'public'::character varying
   */
  app_id: TenantThirdpartyProviders['app_id']
  client_id: string
  client_secret: (string) | null
  /**
   * @default ''::character varying
   */
  client_type: string & {readonly __brand?: 'tenant_thirdparty_provider_clients_client_type'}
  /**
   * @default ''::character varying
   */
  connection_uri_domain: TenantThirdpartyProviders['connection_uri_domain']
  force_pkce: (boolean) | null
  scope: (Array<string | null>) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: TenantThirdpartyProviders['tenant_id']
  third_party_id: TenantThirdpartyProviders['third_party_id']
}
export default TenantThirdpartyProviderClients;

interface TenantThirdpartyProviderClients_InsertParameters {
  additional_config?: (string) | null
  /**
   * @default 'public'::character varying
   */
  app_id?: TenantThirdpartyProviders['app_id']
  client_id: string
  client_secret?: (string) | null
  /**
   * @default ''::character varying
   */
  client_type?: string & {readonly __brand?: 'tenant_thirdparty_provider_clients_client_type'}
  /**
   * @default ''::character varying
   */
  connection_uri_domain?: TenantThirdpartyProviders['connection_uri_domain']
  force_pkce?: (boolean) | null
  scope?: (Array<string | null>) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: TenantThirdpartyProviders['tenant_id']
  third_party_id: TenantThirdpartyProviders['third_party_id']
}
export type {TenantThirdpartyProviderClients_InsertParameters}
