/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tIEcx3L2kRFSNWDm5T2tbeN3KdA5zqQXT10d0Mch6o4dALCyEGUy4LIeGvNgwiE/T0UCGh+BqVbn7NVUll5LjQ==
 */

/* eslint-disable */
// tslint:disable

import AllAuthRecipeUsers from './all_auth_recipe_users'

interface ThirdpartyUserToTenant {
  /**
   * @default 'public'::character varying
   */
  app_id: AllAuthRecipeUsers['app_id']
  /**
   * @default 'public'::character varying
   */
  tenant_id: AllAuthRecipeUsers['tenant_id']
  third_party_id: string
  third_party_user_id: string
  user_id: AllAuthRecipeUsers['user_id']
}
export default ThirdpartyUserToTenant;

interface ThirdpartyUserToTenant_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AllAuthRecipeUsers['app_id']
  /**
   * @default 'public'::character varying
   */
  tenant_id?: AllAuthRecipeUsers['tenant_id']
  third_party_id: string
  third_party_user_id: string
  user_id: AllAuthRecipeUsers['user_id']
}
export type {ThirdpartyUserToTenant_InsertParameters}
