/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JyuEb69vOuCx/9d1jdTDPCYT6FZl2Xg/4F4ccxIpa6Dk9EbHJLfajuovcNDmSuwLB/CDH3OWvoCKk/5MVbGl+A==
 */

/* eslint-disable */
// tslint:disable

import AppIdToUserId from './app_id_to_user_id'

interface ThirdpartyUsers {
  /**
   * @default 'public'::character varying
   */
  app_id: AppIdToUserId['app_id']
  email: string
  third_party_id: string
  third_party_user_id: string
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export default ThirdpartyUsers;

interface ThirdpartyUsers_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AppIdToUserId['app_id']
  email: string
  third_party_id: string
  third_party_user_id: string
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export type {ThirdpartyUsers_InsertParameters}
