/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: kCsSGgt0o3kzKGhnPTg1c0h9o1FoxYn8o4MvERoUcED9SQa49zInrt0I2jUkB3PZFA/+6Vqw8EVjgANvVIwHkA==
 */

/* eslint-disable */
// tslint:disable

import TotpUsers from './totp_users'

interface TotpUserDevices {
  /**
   * @default 'public'::character varying
   */
  app_id: TotpUsers['app_id']
  created_at: (number) | null
  device_name: string & {readonly __brand?: 'totp_user_devices_device_name'}
  period: number
  secret_key: string
  skew: number
  user_id: TotpUsers['user_id']
  verified: boolean
}
export default TotpUserDevices;

interface TotpUserDevices_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: TotpUsers['app_id']
  created_at?: (number) | null
  device_name: string & {readonly __brand?: 'totp_user_devices_device_name'}
  period: number
  secret_key: string
  skew: number
  user_id: TotpUsers['user_id']
  verified: boolean
}
export type {TotpUserDevices_InsertParameters}
