/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Hzi8PX4k38DKaKR/LYqZ0bAW9s+kpqcd8D0ArgiqoxGBMuzealpT2ax0M6dfYOcMNXv/Ev/NTgvdptJyNXYaTg==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface TotpUsers {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  user_id: string & {readonly __brand?: 'totp_users_user_id'}
}
export default TotpUsers;

interface TotpUsers_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  user_id: string & {readonly __brand?: 'totp_users_user_id'}
}
export type {TotpUsers_InsertParameters}
