/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: qm2H9kc7wXB6rr7nkW+Gu6KuvrQPEdTi/O//A3fjlQoMIfrBJXfUPbsI8W+SpxG+9HABXxLYi7IvT0YcPKQqbQ==
 */

/* eslint-disable */
// tslint:disable

import Tenants from './tenants'
import TotpUsers from './totp_users'

interface TotpUsedCodes {
  /**
   * @default 'public'::character varying
   */
  app_id: Tenants['app_id']
  code: string
  created_time_ms: number & {readonly __brand?: 'totp_used_codes_created_time_ms'}
  expiry_time_ms: number
  is_valid: boolean
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
  user_id: TotpUsers['user_id']
}
export default TotpUsedCodes;

interface TotpUsedCodes_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Tenants['app_id']
  code: string
  created_time_ms: number & {readonly __brand?: 'totp_used_codes_created_time_ms'}
  expiry_time_ms: number
  is_valid: boolean
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
  user_id: TotpUsers['user_id']
}
export type {TotpUsedCodes_InsertParameters}
