/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PJXJ+azUUELrLPnyMGKLAJN6HU0bXboSl9UGNDGNi/yRizqTgXWiNfI8YbclPHlaugEjra6OHaFfT4f3P0eMww==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface UserLastActive {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  last_active_time: (number) | null
  user_id: string & {readonly __brand?: 'user_last_active_user_id'}
}
export default UserLastActive;

interface UserLastActive_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  last_active_time?: (number) | null
  user_id: string & {readonly __brand?: 'user_last_active_user_id'}
}
export type {UserLastActive_InsertParameters}
