/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: fZtBwG2INTCywkMdN4A+mYMeqSsMFaKbFa22Gjya2lbcNjmUqAuq5PU4dI/MDZ9mZRYr0HxMkf9GOMuyL+jVWw==
 */

/* eslint-disable */
// tslint:disable

import Tenants from './tenants'

interface UserRoles {
  /**
   * @default 'public'::character varying
   */
  app_id: Tenants['app_id']
  role: string & {readonly __brand?: 'user_roles_role'}
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
  user_id: string & {readonly __brand?: 'user_roles_user_id'}
}
export default UserRoles;

interface UserRoles_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Tenants['app_id']
  role: string & {readonly __brand?: 'user_roles_role'}
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
  user_id: string & {readonly __brand?: 'user_roles_user_id'}
}
export type {UserRoles_InsertParameters}
