/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: bWUUHsyGYFCnwN/wKqvonvKh1Ca06RtiBBas/HT6RGoqsdjcXTGHGT1SdWp6VCdwxQYv9NM/3qV9dCVZbAmnMg==
 */

/* eslint-disable */
// tslint:disable

import Apps from './apps'

interface UserMetadata {
  /**
   * @default 'public'::character varying
   */
  app_id: Apps['app_id']
  user_id: string & {readonly __brand?: 'user_metadata_user_id'}
  user_metadata: string
}
export default UserMetadata;

interface UserMetadata_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Apps['app_id']
  user_id: string & {readonly __brand?: 'user_metadata_user_id'}
  user_metadata: string
}
export type {UserMetadata_InsertParameters}
