/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: mDMeBbSs4ayRuyS/7+CkQUb+2voo91Gwxa/6IQUeKSu06YjzDcJktMePP4O+pYrU4jZH+8fp3dWT/pCN4vkZyg==
 */

/* eslint-disable */
// tslint:disable

import AppIdToUserId from './app_id_to_user_id'

interface UseridMapping {
  /**
   * @default 'public'::character varying
   */
  app_id: AppIdToUserId['app_id']
  external_user_id: string & {readonly __brand?: 'userid_mapping_external_user_id'}
  external_user_id_info: (string) | null
  supertokens_user_id: AppIdToUserId['user_id']
}
export default UseridMapping;

interface UseridMapping_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AppIdToUserId['app_id']
  external_user_id: string & {readonly __brand?: 'userid_mapping_external_user_id'}
  external_user_id_info?: (string) | null
  supertokens_user_id: AppIdToUserId['user_id']
}
export type {UseridMapping_InsertParameters}
