/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: LjZVsbvkwLeh8q0FFGtkltJmhDw7mk56O/ISs/FtDf/18njqzyxTUTmq9BD2+ti5ikEJ4NQlXfxGsQc72misCQ==
 */

/* eslint-disable */
// tslint:disable

import AllAuthRecipeUsers from './all_auth_recipe_users'

interface WebauthnUserToTenant {
  /**
   * @default 'public'::character varying
   */
  app_id: AllAuthRecipeUsers['app_id']
  email: string
  /**
   * @default 'public'::character varying
   */
  tenant_id: AllAuthRecipeUsers['tenant_id']
  user_id: AllAuthRecipeUsers['user_id']
}
export default WebauthnUserToTenant;

interface WebauthnUserToTenant_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AllAuthRecipeUsers['app_id']
  email: string
  /**
   * @default 'public'::character varying
   */
  tenant_id?: AllAuthRecipeUsers['tenant_id']
  user_id: AllAuthRecipeUsers['user_id']
}
export type {WebauthnUserToTenant_InsertParameters}
