/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ILpzGAxCmgfjwmYVpaYS3WQV4MehuJ6Ema2K3FIqEmWGWWccUvakVW0Tr9arXr6QuhlPQLeoPv1rd6vhbI58Fg==
 */

/* eslint-disable */
// tslint:disable

import WebauthnUsers from './webauthn_users'

interface WebauthnCredentials {
  /**
   * @default 'public'::character varying
   */
  app_id: WebauthnUsers['app_id']
  counter: number
  created_at: number
  id: string & {readonly __brand?: 'webauthn_credentials_id'}
  public_key: Buffer
  rp_id: string & {readonly __brand?: 'webauthn_credentials_rp_id'}
  transports: string
  updated_at: number
  user_id: (WebauthnUsers['user_id']) | null
}
export default WebauthnCredentials;

interface WebauthnCredentials_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: WebauthnUsers['app_id']
  counter: number
  created_at: number
  id: string & {readonly __brand?: 'webauthn_credentials_id'}
  public_key: Buffer
  rp_id: string & {readonly __brand?: 'webauthn_credentials_rp_id'}
  transports: string
  updated_at: number
  user_id?: (WebauthnUsers['user_id']) | null
}
export type {WebauthnCredentials_InsertParameters}
