/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: H6eRudxFm23ysK4Uxtgrnh2VfZy49tUTxiBdB7Vih7I3VFmnH2GYTZAJhin0U2PzTBqmogyxSveby4LuiCEV4Q==
 */

/* eslint-disable */
// tslint:disable

import Tenants from './tenants'

interface WebauthnGeneratedOptions {
  /**
   * @default 'public'::character varying
   */
  app_id: Tenants['app_id']
  challenge: string
  created_at: number
  email: (string) | null
  expires_at: number
  id: string & {readonly __brand?: 'webauthn_generated_options_id'}
  origin: string
  rp_id: string
  rp_name: string
  /**
   * @default 'public'::character varying
   */
  tenant_id: Tenants['tenant_id']
  /**
   * @default false
   */
  user_presence_required: boolean
  /**
   * @default 'preferred'::character varying
   */
  user_verification: string
}
export default WebauthnGeneratedOptions;

interface WebauthnGeneratedOptions_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: Tenants['app_id']
  challenge: string
  created_at: number
  email?: (string) | null
  expires_at: number
  id: string & {readonly __brand?: 'webauthn_generated_options_id'}
  origin: string
  rp_id: string
  rp_name: string
  /**
   * @default 'public'::character varying
   */
  tenant_id?: Tenants['tenant_id']
  /**
   * @default false
   */
  user_presence_required?: boolean
  /**
   * @default 'preferred'::character varying
   */
  user_verification?: string
}
export type {WebauthnGeneratedOptions_InsertParameters}
