/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: v5FVmJr2oAgc4xjfBTYr9OQIEjC2+IdQJI6R9qvSrH8rcK0/hZf424wsRojYojnT8eM2EcL4y2zbBU4m4sPFgA==
 */

/* eslint-disable */
// tslint:disable

import AllAuthRecipeUsers from './all_auth_recipe_users'

interface WebauthnAccountRecoveryTokens {
  /**
   * @default 'public'::character varying
   */
  app_id: AllAuthRecipeUsers['app_id']
  email: string
  expires_at: number
  /**
   * @default 'public'::character varying
   */
  tenant_id: AllAuthRecipeUsers['tenant_id']
  token: string & {readonly __brand?: 'webauthn_account_recovery_tokens_token'}
  user_id: AllAuthRecipeUsers['user_id']
}
export default WebauthnAccountRecoveryTokens;

interface WebauthnAccountRecoveryTokens_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AllAuthRecipeUsers['app_id']
  email: string
  expires_at: number
  /**
   * @default 'public'::character varying
   */
  tenant_id?: AllAuthRecipeUsers['tenant_id']
  token: string & {readonly __brand?: 'webauthn_account_recovery_tokens_token'}
  user_id: AllAuthRecipeUsers['user_id']
}
export type {WebauthnAccountRecoveryTokens_InsertParameters}
