/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Cw7J5eKZDQRL/OfyH7SdnxLcf+s+wnncMKGAnPAUlfXpG4mQBgZe7Sc7cJ4ezQ8qTCJ75RNjAzDsySrQkVBfmA==
 */

/* eslint-disable */
// tslint:disable

import AppIdToUserId from './app_id_to_user_id'

interface WebauthnUsers {
  /**
   * @default 'public'::character varying
   */
  app_id: AppIdToUserId['app_id']
  email: string
  rp_id: string
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export default WebauthnUsers;

interface WebauthnUsers_InsertParameters {
  /**
   * @default 'public'::character varying
   */
  app_id?: AppIdToUserId['app_id']
  email: string
  rp_id: string
  time_joined: number
  user_id: AppIdToUserId['user_id']
}
export type {WebauthnUsers_InsertParameters}
