--DROP TABLE Event_Type, Organization, Venue, Event, Attendee, Event_Tickets, Partner, Event_Partner, Event_Ticket_Assignment; 
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Event_Type 
(
	  event_type_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		tenant_id character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
	  event_type_name VARCHAR(50) NULL,
		active boolean NOT NULL
);
COMMENT ON TABLE Event_Type IS 'Table to store different types of events';

--DROP TABLE Organization CASCADE; 
CREATE TABLE Organization 
(
	  organization_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		tenant_id character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
	  name VARCHAR(50) NOT NULL,
	  contact_person VARCHAR(50) ,
	  email character varying(256) COLLATE pg_catalog."default" NOT NULL,
	  phone VARCHAR(25) NULL,
		active boolean NOT NULL
);
-- DROP INDEX IF EXISTS public.Organization_tenant_id_index;

CREATE INDEX IF NOT EXISTS Organization_tenant_id_index
    ON public.Organization USING btree
    (tenant_id COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

COMMENT ON TABLE Organization IS 'Table to store information about organizations';

--DROP TABLE Venue;
CREATE TABLE Venue
(
	  venue_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  tenant_id character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
	  capacity INT NOT NULL, 
	  address_line VARCHAR(60) NULL,
	  city VARCHAR(30) NULL, 
	  state VARCHAR(30) NULL, 
	  postal_code VARCHAR(15) NULL, 
	  country VARCHAR(30) NULL,
		active boolean NOT NULL
);

CREATE INDEX IF NOT EXISTS Venue_tenant_id_index
    ON public.Venue USING btree
    (tenant_id COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

COMMENT ON TABLE Venue IS 'Table to store information about venues';

--DROP TABLE Event;
CREATE TABLE Event 
(
	  event_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		tenant_id character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
		user_id character varying(128) COLLATE pg_catalog."default" NOT NULL,
	  event_Type_id INT NOT NULL,
	  organization_id INT  NOT NULL,
	  venue_id INT NOT NULL,
	  start_date DATE NOT NULL,
	  end_date DATE NULL,
	  budget_estimated MONEY NULL,
	  total_expenditure MONEY NULL,
	  description TEXT NULL,
	  status VARCHAR(20) NULL,
	  estimated_attendance INT NULL,
	  actual_attendance INT NULL,
		active boolean NOT NULL,
	  FOREIGN KEY (event_Type_id) REFERENCES Event_Type(event_Type_id),
	  FOREIGN KEY (organization_id) REFERENCES Organization(organization_id),
	  FOREIGN KEY (venue_id) REFERENCES Venue(venue_id)
);

CREATE INDEX IF NOT EXISTS Event_tenant_id_index
    ON public.Event USING btree
    (tenant_id COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

COMMENT ON TABLE Event IS 'Table to store information about events';

ALTER TABLE Venue
ADD OnlineFlag BIT;

--DROP TABLE Attendee;
CREATE TABLE Attendee 
(
	  attendee_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		tenant_id character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
	  first_name  VARCHAR(50) NOT NULL,
	  last_name VARCHAR(50) NOT NULL,
	  email VARCHAR(50) NOT NULL,
	  phone VARCHAR(25) NULL,
		active boolean NOT NULL
);

CREATE INDEX IF NOT EXISTS Attendee_tenant_id_index
    ON public.Attendee USING btree
    (tenant_id COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

COMMENT ON TABLE Attendee IS 'Table to store information about attendees';

--DROP TABLE Event_Tickets; 
CREATE TABLE Event_Tickets 
(
	ticket_id uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	event_id INT NOT NULL,
	ticket_type VARCHAR(50),
	price MONEY,
	active boolean NOT NULL,
	FOREIGN KEY (event_id) REFERENCES Event(event_id)
);
COMMENT ON TABLE Event_Tickets IS 'Table to store information about event tickets';
/*
ALTER TABLE Event_Tickets
ADD CONSTRAINT PK_ticket_id
PRIMARY KEY(ticket_id);
*/

--DROP TABLE Partner;
CREATE TABLE Partner 
(
	  partner_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		tenant_id character varying(64) COLLATE pg_catalog."default" NOT NULL DEFAULT 'public'::character varying,
	  name VARCHAR(50) NOT NULL,
	  email character varying(256) COLLATE pg_catalog."default" NOT NULL,
	  phone VARCHAR(25) NULL,
		active boolean NOT NULL  
);
COMMENT ON TABLE Partner IS 'Table to store information about partners';

--DROP TABLE Event_Partner;s
CREATE TABLE Event_Partner
(
	  event_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  partner_id INT  NOT NULL,
	  active boolean NOT NULL,
	  FOREIGN KEY (partner_id) REFERENCES Partner(Partner_id)
);
COMMENT ON TABLE Event_Partner IS 'Junction table: one event many partners, one partner many events';


--DROP TABLE Event_Ticket_Assignment;
CREATE TABLE Event_Ticket_Assignment 
(
		ticket_id uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL, -- GUID as the primary key
		attendee_id INT,                               
		event_id INT,                                
		purchase_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),                          
		expiry_date TIMESTAMPTZ NULL,                             
		Price MONEY NULL,
		ticket_type VARCHAR(50) NULL,
		active boolean NOT NULL,	
		FOREIGN KEY (attendee_id) REFERENCES Attendee(attendee_id),
		FOREIGN KEY (event_id) REFERENCES Event(event_id)
);
COMMENT ON TABLE Event_Ticket_Assignment IS 'Junction table: one attendee many events, one event many attendees';	

