/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: U4bfIqyFN/6zovvgn1Jz5UHC5/6q7pId9Lu9ngqy14/zIv0t3/fKJGKHLc5aWBEcHwei6hOqhvyvl7+M7MUxfQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about attendees
 */
interface Attendee {
  active: boolean
  attendee_id: number & {readonly __brand?: 'attendee_attendee_id'}
  email: string
  first_name: string
  last_name: string
  phone: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default Attendee;

/**
 * Table to store information about attendees
 */
interface Attendee_InsertParameters {
  active: boolean
  attendee_id: number & {readonly __brand?: 'attendee_attendee_id'}
  email: string
  first_name: string
  last_name: string
  phone?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {Attendee_InsertParameters}
