/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wF2myjzYeZRL3S8v+Wz+I+q6Qfwniz6a0EBt3iRHR5lo+nx/UdeOkaO7UZtJz72A+3ILWp3wfzg1AJbGgg9lbA==
 */

/* eslint-disable */
// tslint:disable

interface Country {
  active: boolean
  /**
   * @default 'public'::character varying
   */
  country_id: string
  description: string
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default Country;

interface Country_InsertParameters {
  active: boolean
  /**
   * @default 'public'::character varying
   */
  country_id?: string
  description: string
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {Country_InsertParameters}
