/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: govM4u/6aUso+Wv0s8vZhO0gcu7k+HGj2kmWFgyIi4bTq8wEg7N9wOAYGsGStMJK+ZavwD4KnZgI4KqnI0RNKQ==
 */

/* eslint-disable */
// tslint:disable

import Partner from './partner'

/**
 * Junction table: one event many partners, one partner many events
 */
interface EventPartner {
  active: boolean
  event_id: number & {readonly __brand?: 'event_partner_event_id'}
  partner_id: Partner['partner_id']
}
export default EventPartner;

/**
 * Junction table: one event many partners, one partner many events
 */
interface EventPartner_InsertParameters {
  active: boolean
  event_id: number & {readonly __brand?: 'event_partner_event_id'}
  partner_id: Partner['partner_id']
}
export type {EventPartner_InsertParameters}
