/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: LKFnvMnu8dh33FanvF8PddIT9FdzFyiwXyXJP8zaZQqO8NLidBotgoMVv0hx8T+ocai4G2UFLEgP/qeyCkjpNQ==
 */

/* eslint-disable */
// tslint:disable

import Attendee from './attendee'
import Event from './event'

/**
 * Junction table: one attendee many events, one event many attendees
 */
interface EventTicketAssignment {
  active: boolean
  attendee_id: (Attendee['attendee_id']) | null
  event_id: (Event['event_id']) | null
  expiry_date: (Date) | null
  price: (string) | null
  /**
   * @default now()
   */
  purchase_date: Date
  /**
   * @default uuid_generate_v4()
   */
  ticket_id: string & {readonly __brand?: 'event_ticket_assignment_ticket_id'}
  ticket_type: (string) | null
}
export default EventTicketAssignment;

/**
 * Junction table: one attendee many events, one event many attendees
 */
interface EventTicketAssignment_InsertParameters {
  active: boolean
  attendee_id?: (Attendee['attendee_id']) | null
  event_id?: (Event['event_id']) | null
  expiry_date?: (Date) | null
  price?: (string) | null
  /**
   * @default now()
   */
  purchase_date?: Date
  /**
   * @default uuid_generate_v4()
   */
  ticket_id?: string & {readonly __brand?: 'event_ticket_assignment_ticket_id'}
  ticket_type?: (string) | null
}
export type {EventTicketAssignment_InsertParameters}
