/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EoCTo1LrVI4xs5KKiWRk1w3r1dOIrKApEz3tUP30TeQulVEbtQTjucPLxlPtOmVh2WVFe6SPCTxb/sBgsMIMDg==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about event status
 */
interface EventStatus {
  active: boolean
  name: string
  status_id: number & {readonly __brand?: 'event_status_status_id'}
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default EventStatus;

/**
 * Table to store information about event status
 */
interface EventStatus_InsertParameters {
  active: boolean
  name: string
  status_id: number & {readonly __brand?: 'event_status_status_id'}
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {EventStatus_InsertParameters}
