/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: XGxXopCJvfWGIwSsvqlIH7cBCEFhCrp0t8FSzvG34i7YklMOP+Aa1uBUO1m4v3n7olrF/HmH5jV7cz4MqRGN3g==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about organizations
 */
interface Organization {
  active: boolean
  contact_person: (string) | null
  email: string
  name: string
  organization_id: number & {readonly __brand?: 'organization_organization_id'}
  phone: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default Organization;

/**
 * Table to store information about organizations
 */
interface Organization_InsertParameters {
  active: boolean
  contact_person?: (string) | null
  email: string
  name: string
  organization_id: number & {readonly __brand?: 'organization_organization_id'}
  phone?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {Organization_InsertParameters}
