/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: LtRGYsFC4Y08Pmnk/N8/gxOfTDZP+YT5nGkDwo8i0a2U8otBt9vTkQSgrUXajlTpfqr5aq0h6l8OeEJc0i1Qdw==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about partners
 */
interface Partner {
  active: boolean
  email: string
  name: string
  partner_id: number & {readonly __brand?: 'partner_partner_id'}
  phone: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default Partner;

/**
 * Table to store information about partners
 */
interface Partner_InsertParameters {
  active: boolean
  email: string
  name: string
  partner_id: number & {readonly __brand?: 'partner_partner_id'}
  phone?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {Partner_InsertParameters}
