/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: t1rsCWQOSGvS5vraEuCEJJujGC3UFpQxoStwafG7fEbcRHWXLQ22uSrv/vaqIPBLvog/8fKNK8WSrVpuVIFqjg==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about attendees
 */
interface Attendee {
  attendee_id: number & {readonly __brand?: 'attendee_attendee_id'}
  email: string
  first_name: string
  last_name: string
  phone: (string) | null
}
export default Attendee;

/**
 * Table to store information about attendees
 */
interface Attendee_InsertParameters {
  attendee_id: number & {readonly __brand?: 'attendee_attendee_id'}
  email: string
  first_name: string
  last_name: string
  phone?: (string) | null
}
export type {Attendee_InsertParameters}
