/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jw9a3lK8WZsndAuIhU7xWvM7T3NgsJmRF1441f8zaImxK6sLq0DeVd5u6pmRi6w+zdjmZpd8zvE4GHjbwzJxJw==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about attendees
 */
interface Attendee {
  attendee_id: number & {readonly __brand?: 'attendee_attendee_id'}
  email: string
  first_name: string
  last_name: string
  phone: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default Attendee;

/**
 * Table to store information about attendees
 */
interface Attendee_InsertParameters {
  attendee_id: number & {readonly __brand?: 'attendee_attendee_id'}
  email: string
  first_name: string
  last_name: string
  phone?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {Attendee_InsertParameters}
