/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wB0ACPkTw6PAuX4wM8RJQxGXbf43I8y/jPINjCYSwTCuUbyKc7zQl7Ld5KeKsMRwnFrlZBlui55am/5ZqvKhEw==
 */

/* eslint-disable */
// tslint:disable

import Organization from './organization'
import Roles from './roles'

/**
 * Table to store information about employees
 */
interface Employee {
  email: string
  employee_id: number & {readonly __brand?: 'employee_employee_id'}
  first_name: string
  job_title: string
  last_name: string
  organization_id: Organization['organization_id']
  role_id: Roles['role_id']
}
export default Employee;

/**
 * Table to store information about employees
 */
interface Employee_InsertParameters {
  email: string
  employee_id: number & {readonly __brand?: 'employee_employee_id'}
  first_name: string
  job_title: string
  last_name: string
  organization_id: Organization['organization_id']
  role_id: Roles['role_id']
}
export type {Employee_InsertParameters}
