/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ds9SVRoeydifIdxwsmJYQr00S9KFTVAvwGdoAUpvBv6ItpYmzanEzmWWAXS2+cgs2WDICZcOa2GYRMYNs/fxWg==
 */

/* eslint-disable */
// tslint:disable

import Employee from './employee'
import Event from './event'

/**
 * Junction table: one employee many events, one event many employees
 */
interface EventEmployee {
  deadline: (Date) | null
  employee_id: Employee['employee_id']
  event_id: Event['event_id']
  start_date: (Date) | null
  task: (string) | null
  task_completed: (string) | null
}
export default EventEmployee;

/**
 * Junction table: one employee many events, one event many employees
 */
interface EventEmployee_InsertParameters {
  deadline?: (Date) | null
  employee_id: Employee['employee_id']
  event_id: Event['event_id']
  start_date?: (Date) | null
  task?: (string) | null
  task_completed?: (string) | null
}
export type {EventEmployee_InsertParameters}
