/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: zzz8TseeYgsm+aTTe92EcU+dG9B3R2MW3zC954FTynoNzNXGQ1uO3FhvbTZQcHVx15kLtkXPEMhL1+sD8PuWeA==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store different types of events
 */
interface EventType {
  event_type_id: number & {readonly __brand?: 'event_type_event_type_id'}
  event_type_name: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default EventType;

/**
 * Table to store different types of events
 */
interface EventType_InsertParameters {
  event_type_id: number & {readonly __brand?: 'event_type_event_type_id'}
  event_type_name?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {EventType_InsertParameters}
