/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ridfBAIUhRBEjJQk5nhnt0X37Gyup6Hrc3jpcTY1hHbJRwPDF21kJEWWARb0ZpQT6lcBd+zb5ax1Kppb6QKVUw==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store different types of events
 */
interface EventType {
  event_type_id: number & {readonly __brand?: 'event_type_event_type_id'}
  event_type_name: (string) | null
}
export default EventType;

/**
 * Table to store different types of events
 */
interface EventType_InsertParameters {
  event_type_id: number & {readonly __brand?: 'event_type_event_type_id'}
  event_type_name?: (string) | null
}
export type {EventType_InsertParameters}
