/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: QXIUXvB4CqQFP+Zifj0DfFAgKcX2ZflnOK87hr6Lv+fRjpWmjHBBJvx3Yohh3iTvjXY+/lSaFRPDDFEFR7aseQ==
 */

/* eslint-disable */
// tslint:disable

import Event from './event'

/**
 * Table to store information about event tickets
 */
interface EventTickets {
  event_id: Event['event_id']
  price: (string) | null
  /**
   * @default uuid_generate_v4()
   */
  ticket_id: string & {readonly __brand?: 'event_tickets_ticket_id'}
  ticket_type: (string) | null
}
export default EventTickets;

/**
 * Table to store information about event tickets
 */
interface EventTickets_InsertParameters {
  event_id: Event['event_id']
  price?: (string) | null
  /**
   * @default uuid_generate_v4()
   */
  ticket_id?: string & {readonly __brand?: 'event_tickets_ticket_id'}
  ticket_type?: (string) | null
}
export type {EventTickets_InsertParameters}
