/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: +4zhr9Vw5vCKhCBKJFtkd2b0By9kF9OpzRfCbVUMTnKSge3HRNsXkLJI/bwzphXvARDz6tEgGOQSTdMHtfBbUA==
 */

/* eslint-disable */
// tslint:disable

import EventType from './event_type'
import Organization from './organization'
import Venue from './venue'

/**
 * Table to store information about events
 */
interface Event {
  actual_attendance: (number) | null
  budget_estimated: (string) | null
  description: (string) | null
  end_date: (Date) | null
  estimated_attendance: (number) | null
  event_id: number & {readonly __brand?: 'event_event_id'}
  event_type_id: EventType['event_type_id']
  organization_id: Organization['organization_id']
  start_date: Date
  status: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
  total_expenditure: (string) | null
  user_id: string
  venue_id: Venue['venue_id']
}
export default Event;

/**
 * Table to store information about events
 */
interface Event_InsertParameters {
  actual_attendance?: (number) | null
  budget_estimated?: (string) | null
  description?: (string) | null
  end_date?: (Date) | null
  estimated_attendance?: (number) | null
  event_id: number & {readonly __brand?: 'event_event_id'}
  event_type_id: EventType['event_type_id']
  organization_id: Organization['organization_id']
  start_date: Date
  status?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
  total_expenditure?: (string) | null
  user_id: string
  venue_id: Venue['venue_id']
}
export type {Event_InsertParameters}
