/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 4xJvqv7UaN8m548IgSLfEkStumX4Ct8Xafde5NPud6f5mnNIATnYTivtiBEr3yCSYYqAjlVCx8kiCctnk7Myyg==
 */

/* eslint-disable */
// tslint:disable

import Partner from './partner'

/**
 * Junction table: one event many partners, one partner many events
 */
interface EventPartner {
  event_id: number & {readonly __brand?: 'event_partner_event_id'}
  partner_id: Partner['partner_id']
  role: string
}
export default EventPartner;

/**
 * Junction table: one event many partners, one partner many events
 */
interface EventPartner_InsertParameters {
  event_id: number & {readonly __brand?: 'event_partner_event_id'}
  partner_id: Partner['partner_id']
  role: string
}
export type {EventPartner_InsertParameters}
