/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xJUqYVd+OJ9386uu3JfaPOwLTxS9P1uOQpJyMDb35gb2/PCuDzI76SuJ6XCpeJHKv25KKr5p8nsHFVBzZ+qZbw==
 */

/* eslint-disable */
// tslint:disable

import Event from './event'

/**
 * Table to store information about event tickets
 */
interface EventTickets {
  active: boolean
  event_id: Event['event_id']
  price: (string) | null
  /**
   * @default uuid_generate_v4()
   */
  ticket_id: string & {readonly __brand?: 'event_tickets_ticket_id'}
  ticket_type: (string) | null
}
export default EventTickets;

/**
 * Table to store information about event tickets
 */
interface EventTickets_InsertParameters {
  active: boolean
  event_id: Event['event_id']
  price?: (string) | null
  /**
   * @default uuid_generate_v4()
   */
  ticket_id?: string & {readonly __brand?: 'event_tickets_ticket_id'}
  ticket_type?: (string) | null
}
export type {EventTickets_InsertParameters}
