/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: uwnqGcGHk0K65Pf70RNjuwRZZ/4fhcN/KXwovCncr5DC+y5VJVO5gAeCWAs1G1IQtyLpAmoZozzGnhUd9CtA7w==
 */

/* eslint-disable */
// tslint:disable

import EventStatus from './event_status'
import EventType from './event_type'
import Organization from './organization'
import Venue from './venue'

/**
 * Table to store information about events
 */
interface Event {
  active: boolean
  actual_attendance: (number) | null
  budget_estimated: (string) | null
  description: (string) | null
  end_date: Date
  estimated_attendance: (number) | null
  event_id: number & {readonly __brand?: 'event_event_id'}
  event_type_id: EventType['event_type_id']
  organization_id: Organization['organization_id']
  start_date: Date
  status_id: EventStatus['status_id']
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
  total_expenditure: (string) | null
  user_id: string
  venue_id: Venue['venue_id']
}
export default Event;

/**
 * Table to store information about events
 */
interface Event_InsertParameters {
  active: boolean
  actual_attendance?: (number) | null
  budget_estimated?: (string) | null
  description?: (string) | null
  end_date: Date
  estimated_attendance?: (number) | null
  event_id: number & {readonly __brand?: 'event_event_id'}
  event_type_id: EventType['event_type_id']
  organization_id: Organization['organization_id']
  start_date: Date
  status_id: EventStatus['status_id']
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
  total_expenditure?: (string) | null
  user_id: string
  venue_id: Venue['venue_id']
}
export type {Event_InsertParameters}
