/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: GqX/CcEguApZ7HXx0eg2g7IqQEXjkf1/wyOUe8beCilKkuRcuSZ0tAUnwk6TL/OM0OfDftb0cqU40kjAKfMy8Q==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store different types of events
 */
interface EventType {
  active: boolean
  event_type_id: number & {readonly __brand?: 'event_type_event_type_id'}
  event_type_name: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default EventType;

/**
 * Table to store different types of events
 */
interface EventType_InsertParameters {
  active: boolean
  event_type_id: number & {readonly __brand?: 'event_type_event_type_id'}
  event_type_name?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {EventType_InsertParameters}
