/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: +0xOuZmn8jWVVkW8VCR87tY1/THFwbmEkQ2MdbIDWPt0b+rHOQ2jwNpSF1JPIYpX3pSRCA6mD7hl1bScUt+ELA==
 */

/* eslint-disable */
// tslint:disable

import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import Attendee, {Attendee_InsertParameters} from './attendee'
import Country, {Country_InsertParameters} from './country'
import Event, {Event_InsertParameters} from './event'
import EventPartner, {EventPartner_InsertParameters} from './event_partner'
import EventStatus, {EventStatus_InsertParameters} from './event_status'
import EventTicketAssignment, {EventTicketAssignment_InsertParameters} from './event_ticket_assignment'
import EventTickets, {EventTickets_InsertParameters} from './event_tickets'
import EventType, {EventType_InsertParameters} from './event_type'
import Organization, {Organization_InsertParameters} from './organization'
import Partner, {Partner_InsertParameters} from './partner'
import Venue, {Venue_InsertParameters} from './venue'

interface DatabaseSchema {
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  attendee: {record: Attendee, insert: Attendee_InsertParameters};
  country: {record: Country, insert: Country_InsertParameters};
  event: {record: Event, insert: Event_InsertParameters};
  event_partner: {record: EventPartner, insert: EventPartner_InsertParameters};
  event_status: {record: EventStatus, insert: EventStatus_InsertParameters};
  event_ticket_assignment: {record: EventTicketAssignment, insert: EventTicketAssignment_InsertParameters};
  event_tickets: {record: EventTickets, insert: EventTickets_InsertParameters};
  event_type: {record: EventType, insert: EventType_InsertParameters};
  organization: {record: Organization, insert: Organization_InsertParameters};
  partner: {record: Partner, insert: Partner_InsertParameters};
  venue: {record: Venue, insert: Venue_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "event" && c === "locations") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  Attendee,
  Attendee_InsertParameters,
  Country,
  Country_InsertParameters,
  Event,
  EventPartner,
  EventPartner_InsertParameters,
  EventStatus,
  EventStatus_InsertParameters,
  EventTicketAssignment,
  EventTicketAssignment_InsertParameters,
  EventTickets,
  EventTickets_InsertParameters,
  EventType,
  EventType_InsertParameters,
  Event_InsertParameters,
  Organization,
  Organization_InsertParameters,
  Partner,
  Partner_InsertParameters,
  Venue,
  Venue_InsertParameters,
}
