/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 6CEX8DHo+e184Nov03UcJYRr+kmfJuRiUGRSwpmQPjQT5dWjsllSe/vXIi+/4xN+hP5JkZUa/r0DEXLYpDZmiA==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about organizations
 */
interface Organization {
  contact_person: (string) | null
  email: string
  name: string
  organization_id: number & {readonly __brand?: 'organization_organization_id'}
  phone: (string) | null
}
export default Organization;

/**
 * Table to store information about organizations
 */
interface Organization_InsertParameters {
  contact_person?: (string) | null
  email: string
  name: string
  organization_id: number & {readonly __brand?: 'organization_organization_id'}
  phone?: (string) | null
}
export type {Organization_InsertParameters}
