/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: fCjej4y4clcYLOz2ogqBF04GnYLM/M99InDAdMkjXW6nbDUzymXX0joQqdAUQXzQEGPxM4d1WLDvO7J+o/FLrQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about organizations
 */
interface Organization {
  contact_person: (string) | null
  email: string
  name: string
  organization_id: number & {readonly __brand?: 'organization_organization_id'}
  phone: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default Organization;

/**
 * Table to store information about organizations
 */
interface Organization_InsertParameters {
  contact_person?: (string) | null
  email: string
  name: string
  organization_id: number & {readonly __brand?: 'organization_organization_id'}
  phone?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {Organization_InsertParameters}
