/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: M27nbY73XBXMbISs4nMg54bURT09P5DOa0lBIkw/Db9qeCzatXeHS2pg/P9/J/fkw0a1RaLv4+Vpm0f/8uPF2A==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about partners
 */
interface Partner {
  email: string
  name: string
  partner_id: number & {readonly __brand?: 'partner_partner_id'}
  phone: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
}
export default Partner;

/**
 * Table to store information about partners
 */
interface Partner_InsertParameters {
  email: string
  name: string
  partner_id: number & {readonly __brand?: 'partner_partner_id'}
  phone?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
}
export type {Partner_InsertParameters}
