/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /b42wlCvnIon9kB8MV5ymBNBu38mC2Eko1f8TxnyOQmXFYsYpZzU0V0zCm3/LPgmpRLspBeQ+JA5o6KXd8xaDA==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about partners
 */
interface Partner {
  email: string
  name: string
  partner_id: number & {readonly __brand?: 'partner_partner_id'}
  phone: (string) | null
}
export default Partner;

/**
 * Table to store information about partners
 */
interface Partner_InsertParameters {
  email: string
  name: string
  partner_id: number & {readonly __brand?: 'partner_partner_id'}
  phone?: (string) | null
}
export type {Partner_InsertParameters}
