/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Pjt4ScCVjS9TcR6DWTiGSXihAsdM+c1pqv3p3MVuve0gIiYj2eMSfyRSp2y+Drvx1ULJgSRkPeLwpbKOCXF9QQ==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store different user roles
 */
interface Roles {
  role_id: number & {readonly __brand?: 'roles_role_id'}
  role_name: string
}
export default Roles;

/**
 * Table to store different user roles
 */
interface Roles_InsertParameters {
  role_id: number & {readonly __brand?: 'roles_role_id'}
  role_name: string
}
export type {Roles_InsertParameters}
