/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: L4VziyUDbQDbukogbMURoZiBtkjts2/MiJaNwDELjTjx7LarF2t/LDBa5bKS7zOWqDYO8wbd9lDwer5VfmImbw==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about venues
 */
interface Venue {
  address_line: (string) | null
  capacity: number
  city: (string) | null
  country: (string) | null
  onlineflag: (string) | null
  postal_code: (string) | null
  state: (string) | null
  venue_id: number & {readonly __brand?: 'venue_venue_id'}
}
export default Venue;

/**
 * Table to store information about venues
 */
interface Venue_InsertParameters {
  address_line?: (string) | null
  capacity: number
  city?: (string) | null
  country?: (string) | null
  onlineflag?: (string) | null
  postal_code?: (string) | null
  state?: (string) | null
  venue_id: number & {readonly __brand?: 'venue_venue_id'}
}
export type {Venue_InsertParameters}
