/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vf8uQ8w9EZURdIc2l9k2PLUm0ehrRmcijIBDbGWoDU3FmD6Bj3zKvul4sSOjSC3mY/qAgycuvhSSzI96u6+XNg==
 */

/* eslint-disable */
// tslint:disable

/**
 * Table to store information about venues
 */
interface Venue {
  active: boolean
  address_line: (string) | null
  capacity: number
  city: (string) | null
  country: (string) | null
  onlineflag: (string) | null
  postal_code: (string) | null
  state: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id: string
  venue_id: number & {readonly __brand?: 'venue_venue_id'}
}
export default Venue;

/**
 * Table to store information about venues
 */
interface Venue_InsertParameters {
  active: boolean
  address_line?: (string) | null
  capacity: number
  city?: (string) | null
  country?: (string) | null
  onlineflag?: (string) | null
  postal_code?: (string) | null
  state?: (string) | null
  /**
   * @default 'public'::character varying
   */
  tenant_id?: string
  venue_id: number & {readonly __brand?: 'venue_venue_id'}
}
export type {Venue_InsertParameters}
