--CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- Table 8: Event_Type
--DROP TABLE Event_Type, Organization, Venue, Event, Attendee, Event_Tickets, Employee, Partner, Event_Partner, Event_Employee, Event_Ticket_Assignment; 
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Event_Type 
(
	  event_type_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  event_type_name VARCHAR(50) NULL
);

-- Table 6: Organization 

--DROP TABLE Organization CASCADE; 

CREATE TABLE Organization 
(
	  organization_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  name VARCHAR(50) NOT NULL,
	  contact_person VARCHAR(50) ,
	  email VARCHAR(50) NOT NULL,
	  phone VARCHAR(25) NULL
);

-- Table 2: Venue

--DROP TABLE Venue;

CREATE TABLE Venue
(
	  venue_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  capacity INT NOT NULL, 
	  address_line VARCHAR(60) NULL,
	  city VARCHAR(30) NULL, 
	  state VARCHAR(30) NULL, 
	  postal_code VARCHAR(15) NULL, 
	  country VARCHAR(30) NULL
);

-- Table 1:Event

--DROP TABLE Event;

CREATE TABLE Event 
(
	  event_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  event_Type_ID INT NOT NULL,
	  organization_ID INT  NOT NULL,
	  venue_ID INT NOT NULL,
	  start_date DATE NOT NULL,
	  end_date DATE NULL,
	  budget_estimated MONEY NULL,
	  total_expenditure MONEY NULL,
	  description TEXT NULL,
	  status VARCHAR(20) NULL,
	  estimated_attendance INT NULL,
	  actual_attendance INT NULL,
	  FOREIGN KEY (event_Type_ID) REFERENCES Event_Type(event_Type_ID),
	  FOREIGN KEY (organization_ID) REFERENCES Organization(organization_ID),
	  FOREIGN KEY (venue_ID) REFERENCES Venue(venue_ID)
);



ALTER TABLE Venue
ADD OnlineFlag BIT;

-- Table 3: Attendee

--DROP TABLE Attendee;

CREATE TABLE Attendee 
(
	  attendee_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  first_name  VARCHAR(50) NOT NULL,
	  last_name VARCHAR(50) NOT NULL,
	  email VARCHAR(50) NOT NULL,
	  phone VARCHAR(25) NULL
);

-- Table 4: Event_Tickets

--DROP TABLE Event_Tickets; 


CREATE TABLE Event_Tickets 
(
	ticket_ID uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
	event_ID INT NOT NULL,
	ticket_type VARCHAR(50),
	price MONEY,
	FOREIGN KEY (event_ID) REFERENCES Event(event_ID)
);

/*
ALTER TABLE Event_Tickets
ADD CONSTRAINT PK_ticket_ID
PRIMARY KEY(ticket_ID);
*/


-- Table 5: Employee 

--DROP TABLE Employee ;

CREATE TABLE Employee 
(
	  employee_ID  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  organization_ID  INT NOT NULL,
	  first_name VARCHAR(50) NOT NULL,
	  last_name VARCHAR(50) NOT NULL,
	  job_title VARCHAR(50) NOT NULL,
	  email VARCHAR(50) NOT NULL,
	  FOREIGN KEY (organization_ID) REFERENCES Organization(organization_ID)
);



-- Table 7: Partner 

--DROP TABLE Partner;

CREATE TABLE Partner 
(
	  partner_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  name VARCHAR(50) NOT NULL,
	  email VARCHAR(50) NOT NULL,
	  phone VARCHAR(25) NULL
);



-- Table 9: Event_Partner Junction table: one event many partners, one partner many events

--DROP TABLE Event_Partner;

CREATE TABLE Event_Partner
(
	  event_ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	  partner_ID INT  NOT NULL,
	  role VARCHAR(50) NOT NULL,
	  FOREIGN KEY (partner_ID) REFERENCES Partner(Partner_ID)
);


-- Table 10: Event_Employee Junction table: one employee many events, one event many employees

--DROP TABLE Event_Employee; 

CREATE TABLE Event_Employee 
(
	  event_ID INT NOT NULL,
	  employee_ID INT NOT NULL,
	  task VARCHAR(120) NULL,
	  start_date DATE NULL,
	  deadline DATE NULL,
	  task_completed BIT NULL,
	  FOREIGN KEY (event_ID) REFERENCES Event(Event_ID),
	  FOREIGN KEY (employee_ID) REFERENCES Employee(Employee_ID)
);

-- Table 11: Event_Ticket_Assignment junction table: one attendee many events, one event many attendees

--DROP TABLE Event_Ticket_Assignment;

CREATE TABLE Event_Ticket_Assignment 
(
	    ticket_id uuid PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL, -- GUID as the primary key
	    attendee_id INT,                               
	    event_id INT,                                
	    purchase_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),                          
	    expiry_date TIMESTAMPTZ  NULL,                             
	    Price MONEY NULL,
	    ticket_type VARCHAR(50) NULL,
		FOREIGN KEY (attendee_id) REFERENCES Attendee(attendee_id),
		FOREIGN KEY (event_id) REFERENCES Event(event_id)
);