<template>
  <BaseLayout>
    <FormPagesEditor :Pages="PagesMaintenance" />
    Home

    <div class="relative">
      <div class="pbx w-full rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-dark">
        <PageBuilder :showCloseButton="true" @handleClosePageBuilder="closePageBuilder" :showPublishButton="true"
          @handlePublishPageBuilder="handlePublish" :CustomBuilderComponents="TestComponentZero"/>
      </div>
    </div>

    <div v-html="rawHtml"></div>
  </BaseLayout>
</template>
<script setup lang="ts">
import { ref, onMounted } from "vue";
import BaseLayout from "@/layouts/BaseLayout.vue";
import FormPagesEditor from "@/components/FormBuilder/Editor/FormPagesEditor.vue";
import { Pages } from "@/utilities/formBuilder/Pages";
import { type IPages } from "@/interfaces/formBuilder";
import { PageBuilder, getPageBuilder, usePageBuilderModal, type BuilderResourceComponent } from '@myissue/vue-website-page-builder'
import TestComponent from '@/components/ComponentsPageBuilder/TestComponent.vue'
import TestComponentZero from '@/components/ComponentsPageBuilder/TestComponentZero.vue'
const PagesMaintenance = ref<IPages>(new Pages());


const showModal = ref(true)

function closePageBuilder() {
  showModal.value = false
}


const configPageBuilder = {
  updateOrCreate: {
    formType: 'update',
    formName: 'article',
  },
  userSettings: {
    fontFamily: 'Outfit',
  },
  pageSettings: {
    classes: 'sesame-font rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-dark',
  }
}

const rawHtml = ref("")

const pageBuilderService = getPageBuilder()
const { closeAddComponentModal } = usePageBuilderModal()
const handlePublish = () => {
  // Retrieve the latest full page HTML saved by the builder.
  // Save this full string to your backend so global pageSettings can be restored later.
  rawHtml.value = pageBuilderService.getSavedPageHtml() as string
  // Example:
  // await api.updatePost(post.id, { content: latestHtml })
}

interface Component {
  html_code: string
  id: string | null
  title: string
}

const components: BuilderResourceComponent[] = [
  {
    html_code: `<section><div class="relative py-4"><div class="mx-auto max-w-7xl lg:px-4 px-2"><div class="break-words"><h2>This is a component</h2></div></div></div></section>`,
    id: 345345234,
    title: 'Header Example One',
  },
  {
    html_code: `<section><div class="relative py-4"><div class="mx-auto max-w-7xl lg:px-4 px-2"><div class="break-words"><h2>This is another component</h2></div></div></div></section>`,
    id: 987978978,
    title: 'Header Example Two',
  },
]


const loadComponents = async () => {

  for (const component of components) {
    await pageBuilderService.addComponent(component as any)
  }

}

const injectComponentToBuilder = async (componentObject: any) => {

  const component = {
    // ID will be auto-generated by the Page Builder
    id: null,
    html_code: componentObject.html_code,
    title: componentObject.title,
  }

  await pageBuilderService.addComponent(component)
  closeAddComponentModal()
}
onMounted(async () => {
  //await loadComponents()
  const result = await pageBuilderService.startBuilder(configPageBuilder, components)

  console.info('You may inspect this result for message, status, or error:', result)
})

</script>